[phases.setup]
nixPkgs = ["nodejs_24", "chromium"]

[variables]
PUPPETEER_SKIP_DOWNLOAD = "true"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/root/.nix-profile/bin/chromium"

[start]
cmd = "node build/ace.js migration:run --force && node build/bin/server.js"
