export function buildDefaultInvoiceSettings(teamId: string) {
  return {
    teamId,
    billingType: 'quick' as const,
    accentColor: '#6366f1',
    logoUrl: null,
    logoSource: 'custom' as const,
    paymentMethods: ['bank_transfer'],
    customPaymentMethod: null,
    template: 'classique',
    darkMode: false,
    documentFont: 'Lexend',
    eInvoicingEnabled: false,
    pdpProvider: null,
    pdpApiKey: null,
    pdpSandbox: true,
    defaultOperationCategory: 'service' as const,
    defaultSubject: null,
    defaultAcceptanceConditions: null,
    defaultSignatureField: false,
    defaultFreeField: null,
    defaultShowNotes: true,
    defaultVatExempt: false,
    defaultVatRate: 20,
    defaultShowQuantityColumn: true,
    defaultShowUnitColumn: true,
    defaultShowUnitPriceColumn: true,
    defaultShowVatColumn: true,
    defaultFooterText: null,
    defaultShowDeliveryAddress: false,
    defaultLanguage: 'fr',
    quoteFilenamePattern: 'DEV-{numero}',
    invoiceFilenamePattern: 'FAC-{numero}',
    quoteNumberPattern: 'DEV-{numero}',
    invoiceNumberPattern: 'FAC-{numero}',
    footerMode: 'company_info' as const,
    logoBorderRadius: 0,
    nextInvoiceNumber: null,
    nextQuoteNumber: null,
    stripePublishableKey: null,
    stripeSecretKey: null,
    stripeWebhookSecret: null,
    stripeWebhookSecretApp: null,
    collaborationEnabled: false,
    aiEnabled: false,
    aiProvider: 'gemini',
    aiModel: 'nvidia/nemotron-3-super-120b-a12b:free',
  }
}
