/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  account: {
    email: {
      EmailConfirmChange: () => import('#controllers/account/email/email_confirm_change'),
      EmailRequestChange: () => import('#controllers/account/email/email_request_change'),
    },
    profile: {
      Delete: () => import('#controllers/account/profile/delete'),
      ServeAvatar: () => import('#controllers/account/profile/serve_avatar'),
      Show: () => import('#controllers/account/profile/show'),
      Update: () => import('#controllers/account/profile/update'),
      UploadAvatar: () => import('#controllers/account/profile/upload_avatar'),
    },
    providers: {
      Link: () => import('#controllers/account/providers/link'),
      List: () => import('#controllers/account/providers/list'),
      Unlink: () => import('#controllers/account/providers/unlink'),
    },
    security: {
      Password: () => import('#controllers/account/security/password'),
      RevokeSession: () => import('#controllers/account/security/revoke_session'),
      SecurityVerify: () => import('#controllers/account/security/security_verify'),
      Sessions: () => import('#controllers/account/security/sessions'),
    },
    twoFactor: {
      Disable: () => import('#controllers/account/two_factor/disable'),
      Enable: () => import('#controllers/account/two_factor/enable'),
      Setup: () => import('#controllers/account/two_factor/setup'),
    },
  },
  admin: {
    BugReports: () => import('#controllers/admin/bug_reports'),
    Feedbacks: () => import('#controllers/admin/feedbacks'),
    analytics: {
      Overview: () => import('#controllers/admin/analytics/overview'),
      Pages: () => import('#controllers/admin/analytics/pages'),
      Features: () => import('#controllers/admin/analytics/features'),
      Errors: () => import('#controllers/admin/analytics/errors'),
      Performance: () => import('#controllers/admin/analytics/performance'),
      Users: () => import('#controllers/admin/analytics/users'),
    },
  },
  ai: {
    ChatDocument: () => import('#controllers/ai/chat_document'),
    CheckProviders: () => import('#controllers/ai/check_providers'),
    DashboardSummary: () => import('#controllers/ai/dashboard_summary'),
    GenerateDocument: () => import('#controllers/ai/generate_document'),
    GenerateReminder: () => import('#controllers/ai/generate_reminder'),
    GenerateText: () => import('#controllers/ai/generate_text'),
    SuggestInvoiceLines: () => import('#controllers/ai/suggest_invoice_lines'),
  },
  auth: {
    oauth: {
      GoogleAuthUrl: () => import('#controllers/auth/oauth/google_auth_url'),
      GoogleCallback: () => import('#controllers/auth/oauth/google_callback'),
      GoogleDecodeProfile: () => import('#controllers/auth/oauth/google_decode_profile'),
      GoogleRegister: () => import('#controllers/auth/oauth/google_register'),
    },
    registration: {
      Signup: () => import('#controllers/auth/registration/signup'),
    },
    security: {
      CryptoRecover: () => import('#controllers/auth/security/crypto_recover'),
      CryptoWipe: () => import('#controllers/auth/security/crypto_wipe'),
      email: {
        Resend: () => import('#controllers/auth/security/email/resend'),
        Verify: () => import('#controllers/auth/security/email/verify'),
      },
      passwordReset: {
        Request: () => import('#controllers/auth/security/password_reset/request'),
        Reset: () => import('#controllers/auth/security/password_reset/reset'),
      },
      SetupRecoveryKey: () => import('#controllers/auth/security/setup_recovery_key'),
      twoFactor: {
        Verify: () => import('#controllers/auth/security/two_factor/verify'),
      },
    },
    session: {
      Login: () => import('#controllers/auth/session/login'),
      Logout: () => import('#controllers/auth/session/logout'),
      Me: () => import('#controllers/auth/session/me'),
    },
    vault: {
      Unlock: () => import('#controllers/auth/vault/unlock'),
    },
  },
  bugReport: {
    Create: () => import('#controllers/bug_report/create'),
  },
  client: {
    contacts: {
      Destroy: () => import('#controllers/client/contacts/destroy'),
      Index: () => import('#controllers/client/contacts/index'),
      Store: () => import('#controllers/client/contacts/store'),
      Update: () => import('#controllers/client/contacts/update'),
    },
    crud: {
      Create: () => import('#controllers/client/crud/create'),
      Delete: () => import('#controllers/client/crud/delete'),
      List: () => import('#controllers/client/crud/list'),
      Show: () => import('#controllers/client/crud/show'),
      Update: () => import('#controllers/client/crud/update'),
    },
    lookup: {
      SearchSiren: () => import('#controllers/client/lookup/search_siren'),
    },
  },
  company: {
    core: {
      Show: () => import('#controllers/company/core/show'),
      Update: () => import('#controllers/company/core/update'),
    },
    finance: {
      BankAccounts: () => import('#controllers/company/finance/bank_accounts'),
      Bank: () => import('#controllers/company/finance/bank'),
    },
    media: {
      ServeLogo: () => import('#controllers/company/media/serve_logo'),
      UploadLogo: () => import('#controllers/company/media/upload_logo'),
    },
  },
  creditNote: {
    crud: {
      Create: () => import('#controllers/credit_note/crud/create'),
      Delete: () => import('#controllers/credit_note/crud/delete'),
      List: () => import('#controllers/credit_note/crud/list'),
      Show: () => import('#controllers/credit_note/crud/show'),
      Update: () => import('#controllers/credit_note/crud/update'),
    },
    number: {
      NextNumber: () => import('#controllers/credit_note/number/next_number'),
    },
    operations: {
      ConvertInvoice: () => import('#controllers/credit_note/operations/convert_invoice'),
      DownloadPdf: () => import('#controllers/credit_note/operations/download_pdf'),
      Duplicate: () => import('#controllers/credit_note/operations/duplicate'),
      UpdateComment: () => import('#controllers/credit_note/operations/update_comment'),
      UpdateStatus: () => import('#controllers/credit_note/operations/update_status'),
    },
  },
  dashboard: {
    CashFlow: () => import('#controllers/dashboard/cash_flow'),
    Charts: () => import('#controllers/dashboard/charts'),
    SidebarCounts: () => import('#controllers/dashboard/sidebar_counts'),
    Stats: () => import('#controllers/dashboard/stats'),
  },
  einvoicing: {
    Submit: () => import('#controllers/einvoicing/submit'),
    ValidateConnection: () => import('#controllers/einvoicing/validate_connection'),
  },
  email: {
    accounts: {
      Delete: () => import('#controllers/email/accounts/delete'),
      List: () => import('#controllers/email/accounts/list'),
      SetDefault: () => import('#controllers/email/accounts/set_default'),
    },
    logs: {
      List: () => import('#controllers/email/logs/list'),
    },
    oauth: {
      GmailAuthUrl: () => import('#controllers/email/oauth/gmail_auth_url'),
      GmailCallback: () => import('#controllers/email/oauth/gmail_callback'),
    },
    resend: {
      Configure: () => import('#controllers/email/resend/configure'),
    },
    send: {
      SendEmail: () => import('#controllers/email/send/send_email'),
      SendTestEmail: () => import('#controllers/email/send/send_test_email'),
    },
    smtp: {
      Configure: () => import('#controllers/email/smtp/configure'),
    },
    templates: {
      List: () => import('#controllers/email/templates/list'),
      Update: () => import('#controllers/email/templates/update'),
    },
  },
  expense: {
    categories: {
      Create: () => import('#controllers/expense/categories/create'),
      Delete: () => import('#controllers/expense/categories/delete'),
      List: () => import('#controllers/expense/categories/list'),
    },
    crud: {
      Create: () => import('#controllers/expense/crud/create'),
      Delete: () => import('#controllers/expense/crud/delete'),
      List: () => import('#controllers/expense/crud/list'),
      Update: () => import('#controllers/expense/crud/update'),
    },
    ocr: {
      ParseReceipt: () => import('#controllers/expense/ocr/parse_receipt'),
    },
  },
  export: {
    FecExport: () => import('#controllers/export/fec_export'),
  },
  feedback: {
    Create: () => import('#controllers/feedback/create'),
    Mine: () => import('#controllers/feedback/mine'),
  },
  invoice: {
    crud: {
      Create: () => import('#controllers/invoice/crud/create'),
      Delete: () => import('#controllers/invoice/crud/delete'),
      List: () => import('#controllers/invoice/crud/list'),
      Show: () => import('#controllers/invoice/crud/show'),
      Update: () => import('#controllers/invoice/crud/update'),
    },
    export: {
      Pdf: () => import('#controllers/invoice/export/pdf'),
    },
    number: {
      DocumentCount: () => import('#controllers/invoice/number/document_count'),
      NextNumber: () => import('#controllers/invoice/number/next_number'),
      SetNextNumber: () => import('#controllers/invoice/number/set_next_number'),
    },
    operations: {
      ConvertQuote: () => import('#controllers/invoice/operations/convert_quote'),
      Duplicate: () => import('#controllers/invoice/operations/duplicate'),
      UnlinkQuote: () => import('#controllers/invoice/operations/unlink_quote'),
      UpdateComment: () => import('#controllers/invoice/operations/update_comment'),
      UpdateStatus: () => import('#controllers/invoice/operations/update_status'),
    },
    payments: {
      Destroy: () => import('#controllers/invoice/payments/destroy'),
      Index: () => import('#controllers/invoice/payments/index'),
      Store: () => import('#controllers/invoice/payments/store'),
    },
  },
  onboarding: {
    company: {
      CreateCompany: () => import('#controllers/onboarding/company/create_company'),
      SearchCompany: () => import('#controllers/onboarding/company/search_company'),
      SkipCompany: () => import('#controllers/onboarding/company/skip_company'),
    },
    personalization: {
      CompletePersonalization: () => import('#controllers/onboarding/personalization/complete_personalization'),
    },
    team: {
      CreateTeam: () => import('#controllers/onboarding/team/create_team'),
    },
  },
  product: {
    Create: () => import('#controllers/product/create'),
    Delete: () => import('#controllers/product/delete'),
    List: () => import('#controllers/product/list'),
    Show: () => import('#controllers/product/show'),
    Update: () => import('#controllers/product/update'),
  },
  quote: {
    crud: {
      Create: () => import('#controllers/quote/crud/create'),
      Delete: () => import('#controllers/quote/crud/delete'),
      List: () => import('#controllers/quote/crud/list'),
      Show: () => import('#controllers/quote/crud/show'),
      Update: () => import('#controllers/quote/crud/update'),
    },
    export: {
      Pdf: () => import('#controllers/quote/export/pdf'),
    },
    number: {
      DocumentCount: () => import('#controllers/quote/number/document_count'),
      NextNumber: () => import('#controllers/quote/number/next_number'),
      SetNextNumber: () => import('#controllers/quote/number/set_next_number'),
    },
    operations: {
      Duplicate: () => import('#controllers/quote/operations/duplicate'),
      UpdateComment: () => import('#controllers/quote/operations/update_comment'),
      UpdateStatus: () => import('#controllers/quote/operations/update_status'),
    },
  },
  recurringInvoice: {
    crud: {
      Create: () => import('#controllers/recurring_invoice/crud/create'),
      Delete: () => import('#controllers/recurring_invoice/crud/delete'),
      List: () => import('#controllers/recurring_invoice/crud/list'),
      Show: () => import('#controllers/recurring_invoice/crud/show'),
      Update: () => import('#controllers/recurring_invoice/crud/update'),
    },
    operations: {
      Generate: () => import('#controllers/recurring_invoice/operations/generate'),
      ToggleActive: () => import('#controllers/recurring_invoice/operations/toggle_active'),
    },
  },
  reminder: {
    operations: {
      ListReminders: () => import('#controllers/reminder/operations/list_reminders'),
      SendReminder: () => import('#controllers/reminder/operations/send_reminder'),
    },
    settings: {
      Get: () => import('#controllers/reminder/settings/get'),
      Update: () => import('#controllers/reminder/settings/update'),
    },
  },
  settings: {
    invoice: {
      InvoiceLogoUpload: () => import('#controllers/settings/invoice/invoice_logo_upload'),
      InvoiceSettingsShow: () => import('#controllers/settings/invoice/invoice_settings_show'),
      InvoiceSettingsUpdate: () => import('#controllers/settings/invoice/invoice_settings_update'),
      ServeInvoiceLogo: () => import('#controllers/settings/invoice/serve_invoice_logo'),
    },
  },
  tax: {
    VatReport: () => import('#controllers/tax/vat_report'),
  },
  team: {
    core: {
      Create: () => import('#controllers/team/core/create'),
      Delete: () => import('#controllers/team/core/delete'),
      Export: () => import('#controllers/team/core/export'),
      Import: () => import('#controllers/team/core/import'),
      List: () => import('#controllers/team/core/list'),
      Show: () => import('#controllers/team/core/show'),
      Switch: () => import('#controllers/team/core/switch'),
      Update: () => import('#controllers/team/core/update'),
    },
    invitations: {
      AcceptInvite: () => import('#controllers/team/invitations/accept_invite'),
      InviteInfo: () => import('#controllers/team/invitations/invite_info'),
      Invite: () => import('#controllers/team/invitations/invite'),
      RevokeInvite: () => import('#controllers/team/invitations/revoke_invite'),
    },
    media: {
      ServeIcon: () => import('#controllers/team/media/serve_icon'),
      UploadIcon: () => import('#controllers/team/media/upload_icon'),
    },
    members: {
      Members: () => import('#controllers/team/members/members'),
      RemoveMember: () => import('#controllers/team/members/remove_member'),
      TransferOwnership: () => import('#controllers/team/members/transfer_ownership'),
      UpdateRole: () => import('#controllers/team/members/update_role'),
    },
  },
  analytics: {
    Ingest: () => import('#controllers/analytics/ingest'),
    Consent: () => import('#controllers/analytics/consent'),
  },
}
