/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  account: {
    email: {
      EmailConfirmChange: () => import('#controllers/account/email/email_confirm_change'),
      EmailRequestChange: () => import('#controllers/account/email/email_request_change'),
    },
    profile: {
      Delete: () => import('#controllers/account/profile/delete'),
      ServeAvatar: () => import('#controllers/account/profile/serve_avatar'),
      Show: () => import('#controllers/account/profile/show'),
      Update: () => import('#controllers/account/profile/update'),
      UploadAvatar: () => import('#controllers/account/profile/upload_avatar'),
    },
    providers: {
      Link: () => import('#controllers/account/providers/link'),
      List: () => import('#controllers/account/providers/list'),
      Unlink: () => import('#controllers/account/providers/unlink'),
    },
    security: {
      Password: () => import('#controllers/account/security/password'),
      RevokeSession: () => import('#controllers/account/security/revoke_session'),
      SecurityVerify: () => import('#controllers/account/security/security_verify'),
      Sessions: () => import('#controllers/account/security/sessions'),
    },
    twoFactor: {
      Disable: () => import('#controllers/account/two_factor/disable'),
      Enable: () => import('#controllers/account/two_factor/enable'),
      Setup: () => import('#controllers/account/two_factor/setup'),
    },
  },
  auth: {
    oauth: {
      GoogleAuthUrl: () => import('#controllers/auth/oauth/google_auth_url'),
      GoogleCallback: () => import('#controllers/auth/oauth/google_callback'),
      GoogleDecodeProfile: () => import('#controllers/auth/oauth/google_decode_profile'),
      GoogleRegister: () => import('#controllers/auth/oauth/google_register'),
    },
    registration: {
      Signup: () => import('#controllers/auth/registration/signup'),
    },
    security: {
      CryptoRecover: () => import('#controllers/auth/security/crypto_recover'),
      CryptoWipe: () => import('#controllers/auth/security/crypto_wipe'),
      email: {
        Resend: () => import('#controllers/auth/security/email/resend'),
        Verify: () => import('#controllers/auth/security/email/verify'),
      },
      passwordReset: {
        Request: () => import('#controllers/auth/security/password_reset/request'),
        Reset: () => import('#controllers/auth/security/password_reset/reset'),
      },
      twoFactor: {
        Verify: () => import('#controllers/auth/security/two_factor/verify'),
      },
    },
    session: {
      Login: () => import('#controllers/auth/session/login'),
      Logout: () => import('#controllers/auth/session/logout'),
      Me: () => import('#controllers/auth/session/me'),
    },
    vault: {
      Unlock: () => import('#controllers/auth/vault/unlock'),
    },
  },
  client: {
    crud: {
      Create: () => import('#controllers/client/crud/create'),
      Delete: () => import('#controllers/client/crud/delete'),
      List: () => import('#controllers/client/crud/list'),
      Show: () => import('#controllers/client/crud/show'),
      Update: () => import('#controllers/client/crud/update'),
    },
    lookup: {
      SearchSiren: () => import('#controllers/client/lookup/search_siren'),
    },
  },
  company: {
    core: {
      Show: () => import('#controllers/company/core/show'),
      Update: () => import('#controllers/company/core/update'),
    },
    finance: {
      BankAccounts: () => import('#controllers/company/finance/bank_accounts'),
      Bank: () => import('#controllers/company/finance/bank'),
    },
    media: {
      ServeLogo: () => import('#controllers/company/media/serve_logo'),
      UploadLogo: () => import('#controllers/company/media/upload_logo'),
    },
  },
  dashboard: {
    Charts: () => import('#controllers/dashboard/charts'),
    SidebarCounts: () => import('#controllers/dashboard/sidebar_counts'),
    Stats: () => import('#controllers/dashboard/stats'),
  },
  einvoicing: {
    Submit: () => import('#controllers/einvoicing/submit'),
    ValidateConnection: () => import('#controllers/einvoicing/validate_connection'),
  },
  email: {
    accounts: {
      Delete: () => import('#controllers/email/accounts/delete'),
      List: () => import('#controllers/email/accounts/list'),
      SetDefault: () => import('#controllers/email/accounts/set_default'),
    },
    logs: {
      List: () => import('#controllers/email/logs/list'),
    },
    oauth: {
      GmailAuthUrl: () => import('#controllers/email/oauth/gmail_auth_url'),
      GmailCallback: () => import('#controllers/email/oauth/gmail_callback'),
    },
    resend: {
      Configure: () => import('#controllers/email/resend/configure'),
    },
    send: {
      SendEmail: () => import('#controllers/email/send/send_email'),
      SendTestEmail: () => import('#controllers/email/send/send_test_email'),
    },
    smtp: {
      Configure: () => import('#controllers/email/smtp/configure'),
    },
  },
  invoice: {
    crud: {
      Create: () => import('#controllers/invoice/crud/create'),
      Delete: () => import('#controllers/invoice/crud/delete'),
      List: () => import('#controllers/invoice/crud/list'),
      Show: () => import('#controllers/invoice/crud/show'),
      Update: () => import('#controllers/invoice/crud/update'),
    },
    export: {
      Pdf: () => import('#controllers/invoice/export/pdf'),
    },
    number: {
      DocumentCount: () => import('#controllers/invoice/number/document_count'),
      NextNumber: () => import('#controllers/invoice/number/next_number'),
      SetNextNumber: () => import('#controllers/invoice/number/set_next_number'),
    },
    operations: {
      ConvertQuote: () => import('#controllers/invoice/operations/convert_quote'),
      Duplicate: () => import('#controllers/invoice/operations/duplicate'),
      UnlinkQuote: () => import('#controllers/invoice/operations/unlink_quote'),
      UpdateComment: () => import('#controllers/invoice/operations/update_comment'),
      UpdateStatus: () => import('#controllers/invoice/operations/update_status'),
    },
  },
  onboarding: {
    company: {
      CreateCompany: () => import('#controllers/onboarding/company/create_company'),
      SearchCompany: () => import('#controllers/onboarding/company/search_company'),
      SkipCompany: () => import('#controllers/onboarding/company/skip_company'),
    },
    personalization: {
      CompletePersonalization: () => import('#controllers/onboarding/personalization/complete_personalization'),
    },
    team: {
      CreateTeam: () => import('#controllers/onboarding/team/create_team'),
    },
  },
  quote: {
    crud: {
      Create: () => import('#controllers/quote/crud/create'),
      Delete: () => import('#controllers/quote/crud/delete'),
      List: () => import('#controllers/quote/crud/list'),
      Show: () => import('#controllers/quote/crud/show'),
      Update: () => import('#controllers/quote/crud/update'),
    },
    export: {
      Pdf: () => import('#controllers/quote/export/pdf'),
    },
    number: {
      DocumentCount: () => import('#controllers/quote/number/document_count'),
      NextNumber: () => import('#controllers/quote/number/next_number'),
      SetNextNumber: () => import('#controllers/quote/number/set_next_number'),
    },
    operations: {
      Duplicate: () => import('#controllers/quote/operations/duplicate'),
      UpdateComment: () => import('#controllers/quote/operations/update_comment'),
      UpdateStatus: () => import('#controllers/quote/operations/update_status'),
    },
  },
  settings: {
    invoice: {
      InvoiceLogoUpload: () => import('#controllers/settings/invoice/invoice_logo_upload'),
      InvoiceSettingsShow: () => import('#controllers/settings/invoice/invoice_settings_show'),
      InvoiceSettingsUpdate: () => import('#controllers/settings/invoice/invoice_settings_update'),
      ServeInvoiceLogo: () => import('#controllers/settings/invoice/serve_invoice_logo'),
    },
  },
  team: {
    core: {
      Create: () => import('#controllers/team/core/create'),
      Delete: () => import('#controllers/team/core/delete'),
      Export: () => import('#controllers/team/core/export'),
      Import: () => import('#controllers/team/core/import'),
      List: () => import('#controllers/team/core/list'),
      Show: () => import('#controllers/team/core/show'),
      Switch: () => import('#controllers/team/core/switch'),
      Update: () => import('#controllers/team/core/update'),
    },
    invitations: {
      AcceptInvite: () => import('#controllers/team/invitations/accept_invite'),
      InviteInfo: () => import('#controllers/team/invitations/invite_info'),
      Invite: () => import('#controllers/team/invitations/invite'),
      RevokeInvite: () => import('#controllers/team/invitations/revoke_invite'),
    },
    media: {
      ServeIcon: () => import('#controllers/team/media/serve_icon'),
      UploadIcon: () => import('#controllers/team/media/upload_icon'),
    },
    members: {
      Members: () => import('#controllers/team/members/members'),
      RemoveMember: () => import('#controllers/team/members/remove_member'),
      TransferOwnership: () => import('#controllers/team/members/transfer_ownership'),
      UpdateRole: () => import('#controllers/team/members/update_role'),
    },
  },
}
