/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AiUsageLogSchema extends BaseModel {
  static $columns = ['createdAt', 'endpoint', 'id', 'model', 'teamId', 'userId'] as const
  $columns = AiUsageLogSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endpoint: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare model: string
  @column()
  declare teamId: string
  @column()
  declare userId: string
}

export class AnalyticsErrorSchema extends BaseModel {
  static $columns = ['browser', 'createdAt', 'errorMessage', 'errorMessageFullEncrypted', 'errorType', 'fingerprint', 'id', 'isResolved', 'occurrenceCount', 'os', 'pagePath', 'sessionId', 'stackTraceEncrypted', 'timestamp', 'userId'] as const
  $columns = AnalyticsErrorSchema.$columns
  @column()
  declare browser: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errorMessage: string
  @column()
  declare errorMessageFullEncrypted: string | null
  @column()
  declare errorType: string
  @column()
  declare fingerprint: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isResolved: boolean | null
  @column()
  declare occurrenceCount: number | null
  @column()
  declare os: string | null
  @column()
  declare pagePath: string | null
  @column()
  declare sessionId: string | null
  @column()
  declare stackTraceEncrypted: string | null
  @column.dateTime()
  declare timestamp: DateTime
  @column()
  declare userId: string | null
}

export class AnalyticsEventSchema extends BaseModel {
  static $columns = ['createdAt', 'eventName', 'eventType', 'id', 'metadata', 'metadataEncrypted', 'pagePath', 'pagePathFullEncrypted', 'sessionId', 'timestamp', 'userId'] as const
  $columns = AnalyticsEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventName: string
  @column()
  declare eventType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare metadata: any | null
  @column()
  declare metadataEncrypted: string | null
  @column()
  declare pagePath: string | null
  @column()
  declare pagePathFullEncrypted: string | null
  @column()
  declare sessionId: string
  @column.dateTime()
  declare timestamp: DateTime
  @column()
  declare userId: string | null
}

export class AnalyticsPerformanceSchema extends BaseModel {
  static $columns = ['connectionType', 'createdAt', 'deviceType', 'id', 'metricName', 'metricValue', 'pagePath', 'rating', 'sessionId', 'timestamp', 'userId'] as const
  $columns = AnalyticsPerformanceSchema.$columns
  @column()
  declare connectionType: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceType: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare metricName: string
  @column()
  declare metricValue: string
  @column()
  declare pagePath: string | null
  @column()
  declare rating: string
  @column()
  declare sessionId: string | null
  @column.dateTime()
  declare timestamp: DateTime
  @column()
  declare userId: string | null
}

export class AnalyticsSessionSchema extends BaseModel {
  static $columns = ['browser', 'browserVersion', 'cityEncrypted', 'country', 'countryNameEncrypted', 'createdAt', 'deviceType', 'durationSeconds', 'endedAt', 'entryPage', 'eventCount', 'exitPage', 'id', 'ipAddressEncrypted', 'ipHash', 'isAuthenticated', 'language', 'os', 'pageCount', 'referrerEncrypted', 'screenHeight', 'screenWidth', 'sessionToken', 'startedAt', 'updatedAt', 'userAgentEncrypted', 'userId'] as const
  $columns = AnalyticsSessionSchema.$columns
  @column()
  declare browser: string | null
  @column()
  declare browserVersion: string | null
  @column()
  declare cityEncrypted: string | null
  @column()
  declare country: string | null
  @column()
  declare countryNameEncrypted: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceType: string | null
  @column()
  declare durationSeconds: number | null
  @column.dateTime()
  declare endedAt: DateTime | null
  @column()
  declare entryPage: string | null
  @column()
  declare eventCount: number | null
  @column()
  declare exitPage: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddressEncrypted: string | null
  @column()
  declare ipHash: string
  @column()
  declare isAuthenticated: boolean | null
  @column()
  declare language: string | null
  @column()
  declare os: string | null
  @column()
  declare pageCount: number | null
  @column()
  declare referrerEncrypted: string | null
  @column()
  declare screenHeight: number | null
  @column()
  declare screenWidth: number | null
  @column()
  declare sessionToken: string
  @column.dateTime()
  declare startedAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userAgentEncrypted: string | null
  @column()
  declare userId: string | null
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'id', 'ipAddress', 'metadata', 'resourceId', 'resourceType', 'severity', 'userAgent', 'userId'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: any | null
  @column()
  declare resourceId: string | null
  @column()
  declare resourceType: string
  @column()
  declare severity: string
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'encryptedKek', 'expiresAt', 'hash', 'id', 'ipAddress', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt', 'userAgent'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare encryptedKek: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
}

export class AuthProviderSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'displayName', 'email', 'id', 'provider', 'providerUserId', 'updatedAt', 'userId'] as const
  $columns = AuthProviderSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayName: string | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare provider: string
  @column()
  declare providerUserId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class BankAccountSchema extends BaseModel {
  static $columns = ['bankName', 'bic', 'createdAt', 'iban', 'id', 'isDefault', 'label', 'teamId', 'updatedAt'] as const
  $columns = BankAccountSchema.$columns
  @column()
  declare bankName: string | null
  @column()
  declare bic: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare iban: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDefault: boolean
  @column()
  declare label: string
  @column()
  declare teamId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BugReportSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'severity', 'status', 'stepsToReproduce', 'subject', 'updatedAt', 'userId'] as const
  $columns = BugReportSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare severity: string
  @column()
  declare status: string
  @column()
  declare stepsToReproduce: string | null
  @column()
  declare subject: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class ClientContactSchema extends BaseModel {
  static $columns = ['clientId', 'createdAt', 'email', 'firstName', 'id', 'includeInEmails', 'isPrimary', 'lastName', 'notes', 'phone', 'role', 'teamId', 'updatedAt'] as const
  $columns = ClientContactSchema.$columns
  @column()
  declare clientId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare includeInEmails: boolean
  @column()
  declare isPrimary: boolean
  @column()
  declare lastName: string | null
  @column()
  declare notes: string | null
  @column()
  declare phone: string | null
  @column()
  declare role: string | null
  @column()
  declare teamId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClientSchema extends BaseModel {
  static $columns = ['address', 'addressComplement', 'b2BContactId', 'city', 'companyName', 'country', 'createdAt', 'email', 'firstName', 'id', 'includeInEmails', 'lastName', 'notes', 'phone', 'postalCode', 'siren', 'siret', 'teamId', 'type', 'updatedAt', 'vatNumber'] as const
  $columns = ClientSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare addressComplement: string | null
  @column()
  declare b2BContactId: number | null
  @column()
  declare city: string | null
  @column()
  declare companyName: string | null
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare includeInEmails: boolean
  @column()
  declare lastName: string | null
  @column()
  declare notes: string | null
  @column()
  declare phone: string | null
  @column()
  declare postalCode: string | null
  @column()
  declare siren: string | null
  @column()
  declare siret: string | null
  @column()
  declare teamId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vatNumber: string | null
}

export class CompanySchema extends BaseModel {
  static $columns = ['addressLine1', 'addressLine2', 'bankName', 'bic', 'city', 'country', 'createdAt', 'currency', 'email', 'iban', 'id', 'legalForm', 'legalName', 'logoUrl', 'paymentConditions', 'phone', 'postalCode', 'siren', 'siret', 'teamId', 'tradeName', 'updatedAt', 'vatNumber', 'website'] as const
  $columns = CompanySchema.$columns
  @column()
  declare addressLine1: string | null
  @column()
  declare addressLine2: string | null
  @column()
  declare bankName: string | null
  @column()
  declare bic: string | null
  @column()
  declare city: string | null
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare email: string | null
  @column()
  declare iban: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare legalForm: string | null
  @column()
  declare legalName: string
  @column()
  declare logoUrl: string | null
  @column()
  declare paymentConditions: string | null
  @column()
  declare phone: string | null
  @column()
  declare postalCode: string | null
  @column()
  declare siren: string | null
  @column()
  declare siret: string | null
  @column()
  declare teamId: string
  @column()
  declare tradeName: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vatNumber: string | null
  @column()
  declare website: string | null
}

export class CookieConsentSchema extends BaseModel {
  static $columns = ['action', 'consentAnalytics', 'consentEssential', 'createdAt', 'id', 'ipAddressEncrypted', 'userAgentEncrypted', 'userId', 'visitorId'] as const
  $columns = CookieConsentSchema.$columns
  @column()
  declare action: string
  @column()
  declare consentAnalytics: boolean | null
  @column()
  declare consentEssential: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddressEncrypted: string | null
  @column()
  declare userAgentEncrypted: string | null
  @column()
  declare userId: string | null
  @column()
  declare visitorId: string
}

export class CreditNoteLineSchema extends BaseModel {
  static $columns = ['createdAt', 'creditNoteId', 'description', 'id', 'position', 'quantity', 'saleType', 'total', 'unit', 'unitPrice', 'updatedAt', 'vatRate'] as const
  $columns = CreditNoteLineSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creditNoteId: string
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare position: number
  @column()
  declare quantity: string
  @column()
  declare saleType: string | null
  @column()
  declare total: string
  @column()
  declare unit: string | null
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vatRate: string
}

export class CreditNoteSchema extends BaseModel {
  static $columns = ['accentColor', 'acceptanceConditions', 'billingType', 'clientId', 'clientSiren', 'clientSnapshot', 'clientVatNumber', 'comment', 'companySnapshot', 'createdAt', 'creditNoteNumber', 'deliveryAddress', 'documentTitle', 'freeField', 'globalDiscountType', 'globalDiscountValue', 'id', 'issueDate', 'language', 'logoUrl', 'notes', 'operationCategory', 'reason', 'signatureField', 'sourceInvoiceId', 'status', 'subject', 'subtotal', 'taxAmount', 'teamId', 'total', 'updatedAt', 'vatExemptReason'] as const
  $columns = CreditNoteSchema.$columns
  @column()
  declare accentColor: string
  @column()
  declare acceptanceConditions: string | null
  @column()
  declare billingType: string
  @column()
  declare clientId: string | null
  @column()
  declare clientSiren: string | null
  @column()
  declare clientSnapshot: string | null
  @column()
  declare clientVatNumber: string | null
  @column()
  declare comment: string | null
  @column()
  declare companySnapshot: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creditNoteNumber: string
  @column()
  declare deliveryAddress: string | null
  @column()
  declare documentTitle: string | null
  @column()
  declare freeField: string | null
  @column()
  declare globalDiscountType: string
  @column()
  declare globalDiscountValue: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare issueDate: string
  @column()
  declare language: string
  @column()
  declare logoUrl: string | null
  @column()
  declare notes: string | null
  @column()
  declare operationCategory: string | null
  @column()
  declare reason: string | null
  @column()
  declare signatureField: boolean
  @column()
  declare sourceInvoiceId: string | null
  @column()
  declare status: string
  @column()
  declare subject: string | null
  @column()
  declare subtotal: string
  @column()
  declare taxAmount: string
  @column()
  declare teamId: string
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vatExemptReason: string
}

export class DocumentShareLinkSchema extends BaseModel {
  static $columns = ['autoExpire', 'createdAt', 'createdByUserId', 'documentId', 'documentType', 'expiresAt', 'id', 'isActive', 'permission', 'teamId', 'token', 'updatedAt', 'visibility'] as const
  $columns = DocumentShareLinkSchema.$columns
  @column()
  declare autoExpire: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: string
  @column()
  declare documentId: string
  @column()
  declare documentType: any
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare permission: any
  @column()
  declare teamId: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare visibility: any
}

export class DocumentShareSchema extends BaseModel {
  static $columns = ['createdAt', 'documentId', 'documentType', 'id', 'permission', 'sharedByUserId', 'sharedWithEmail', 'sharedWithUserId', 'status', 'teamId', 'updatedAt'] as const
  $columns = DocumentShareSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare documentId: string
  @column()
  declare documentType: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare permission: any
  @column()
  declare sharedByUserId: string
  @column()
  declare sharedWithEmail: string | null
  @column()
  declare sharedWithUserId: string | null
  @column()
  declare status: any
  @column()
  declare teamId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EinvoicingSubmissionSchema extends BaseModel {
  static $columns = ['createdAt', 'documentId', 'documentNumber', 'documentType', 'externalId', 'id', 'lastCheckedAt', 'lifecycleEvents', 'provider', 'status', 'statusMessage', 'submittedAt', 'submittedByUserId', 'teamId', 'trackingId', 'updatedAt', 'xmlContent'] as const
  $columns = EinvoicingSubmissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare documentId: string
  @column()
  declare documentNumber: string
  @column()
  declare documentType: any
  @column()
  declare externalId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastCheckedAt: DateTime | null
  @column()
  declare lifecycleEvents: any
  @column()
  declare provider: string
  @column()
  declare status: any
  @column()
  declare statusMessage: string | null
  @column.dateTime()
  declare submittedAt: DateTime | null
  @column()
  declare submittedByUserId: string | null
  @column()
  declare teamId: string
  @column()
  declare trackingId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare xmlContent: string | null
}

export class EmailAccountSchema extends BaseModel {
  static $columns = ['accessToken', 'createdAt', 'displayName', 'email', 'id', 'isActive', 'isDefault', 'provider', 'refreshToken', 'smtpHost', 'smtpPassword', 'smtpPort', 'smtpUsername', 'teamId', 'tokenExpiresAt', 'updatedAt'] as const
  $columns = EmailAccountSchema.$columns
  @column()
  declare accessToken: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayName: string | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare isDefault: boolean
  @column()
  declare provider: string
  @column()
  declare refreshToken: string | null
  @column()
  declare smtpHost: string | null
  @column()
  declare smtpPassword: string | null
  @column()
  declare smtpPort: number | null
  @column()
  declare smtpUsername: string | null
  @column()
  declare teamId: string
  @column.dateTime()
  declare tokenExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EmailLogSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'documentId', 'documentNumber', 'documentType', 'emailType', 'errorMessage', 'fromEmail', 'id', 'status', 'subject', 'teamId', 'toEmail', 'updatedAt'] as const
  $columns = EmailLogSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare documentId: string
  @column()
  declare documentNumber: string
  @column()
  declare documentType: string
  @column()
  declare emailType: string
  @column()
  declare errorMessage: string | null
  @column()
  declare fromEmail: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare status: string
  @column()
  declare subject: string | null
  @column()
  declare teamId: string
  @column()
  declare toEmail: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EmailTemplateSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'id', 'subject', 'teamId', 'templateType', 'updatedAt'] as const
  $columns = EmailTemplateSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare subject: string
  @column()
  declare teamId: string
  @column()
  declare templateType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ExpenseCategorySchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'id', 'name', 'teamId', 'updatedAt'] as const
  $columns = ExpenseCategorySchema.$columns
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare teamId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExpenseSchema extends BaseModel {
  static $columns = ['amount', 'categoryId', 'createdAt', 'currency', 'description', 'expenseDate', 'id', 'isDeductible', 'notes', 'paymentMethod', 'receiptUrl', 'supplier', 'teamId', 'updatedAt', 'vatAmount', 'vatRate'] as const
  $columns = ExpenseSchema.$columns
  @column()
  declare amount: string
  @column()
  declare categoryId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare description: string
  @column()
  declare expenseDate: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDeductible: boolean
  @column()
  declare notes: string | null
  @column()
  declare paymentMethod: string | null
  @column()
  declare receiptUrl: string | null
  @column()
  declare supplier: string | null
  @column()
  declare teamId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vatAmount: string
  @column()
  declare vatRate: string
}

export class FeedbackSchema extends BaseModel {
  static $columns = ['comment', 'createdAt', 'id', 'rating', 'updatedAt', 'userId'] as const
  $columns = FeedbackSchema.$columns
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare rating: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class InvoiceLineSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'invoiceId', 'position', 'quantity', 'saleType', 'total', 'unit', 'unitPrice', 'updatedAt', 'vatRate'] as const
  $columns = InvoiceLineSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare invoiceId: string
  @column()
  declare position: number
  @column()
  declare quantity: string
  @column()
  declare saleType: string | null
  @column()
  declare total: string
  @column()
  declare unit: string | null
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vatRate: string
}

export class InvoicePaymentSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'id', 'invoiceId', 'notes', 'paymentDate', 'paymentMethod', 'teamId', 'updatedAt'] as const
  $columns = InvoicePaymentSchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare invoiceId: string
  @column()
  declare notes: string | null
  @column()
  declare paymentDate: string
  @column()
  declare paymentMethod: string | null
  @column()
  declare teamId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InvoiceSettingSchema extends BaseModel {
  static $columns = ['accentColor', 'aiApiKeyClaude', 'aiApiKeyGemini', 'aiApiKeyGroq', 'aiCustomApiKey', 'aiEnabled', 'aiKeyMode', 'aiModel', 'aiProvider', 'b2BAccountId', 'b2BEnterpriseSize', 'b2BEreportingEnabled', 'b2BNafCode', 'b2BTypeOperation', 'billingType', 'collaborationEnabled', 'createdAt', 'creditNoteFilenamePattern', 'customPaymentMethod', 'darkMode', 'defaultAcceptanceConditions', 'defaultFooterText', 'defaultFreeField', 'defaultLanguage', 'defaultOperationCategory', 'defaultShowDeliveryAddress', 'defaultShowNotes', 'defaultShowQuantityColumn', 'defaultShowUnitColumn', 'defaultShowUnitPriceColumn', 'defaultShowVatColumn', 'defaultSignatureField', 'defaultSubject', 'defaultVatExempt', 'defaultVatRate', 'documentFont', 'eInvoicingEnabled', 'footerMode', 'id', 'invoiceFilenamePattern', 'invoiceNumberPattern', 'logoBorderRadius', 'logoSource', 'logoUrl', 'nextCreditNoteNumber', 'nextInvoiceNumber', 'nextQuoteNumber', 'paymentMethods', 'pdpApiKey', 'pdpProvider', 'pdpSandbox', 'quoteFilenamePattern', 'quoteNumberPattern', 'stripePublishableKey', 'stripeSecretKey', 'stripeWebhookSecret', 'stripeWebhookSecretApp', 'teamId', 'template', 'updatedAt'] as const
  $columns = InvoiceSettingSchema.$columns
  @column()
  declare accentColor: string
  @column()
  declare aiApiKeyClaude: string | null
  @column()
  declare aiApiKeyGemini: string | null
  @column()
  declare aiApiKeyGroq: string | null
  @column()
  declare aiCustomApiKey: string | null
  @column()
  declare aiEnabled: boolean
  @column()
  declare aiKeyMode: string
  @column()
  declare aiModel: string
  @column()
  declare aiProvider: string | null
  @column()
  declare b2BAccountId: string | null
  @column()
  declare b2BEnterpriseSize: string | null
  @column()
  declare b2BEreportingEnabled: boolean
  @column()
  declare b2BNafCode: string | null
  @column()
  declare b2BTypeOperation: string | null
  @column()
  declare billingType: string
  @column()
  declare collaborationEnabled: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creditNoteFilenamePattern: string
  @column()
  declare customPaymentMethod: string | null
  @column()
  declare darkMode: boolean
  @column()
  declare defaultAcceptanceConditions: string | null
  @column()
  declare defaultFooterText: string | null
  @column()
  declare defaultFreeField: string | null
  @column()
  declare defaultLanguage: string | null
  @column()
  declare defaultOperationCategory: string | null
  @column()
  declare defaultShowDeliveryAddress: boolean | null
  @column()
  declare defaultShowNotes: boolean | null
  @column()
  declare defaultShowQuantityColumn: boolean
  @column()
  declare defaultShowUnitColumn: boolean
  @column()
  declare defaultShowUnitPriceColumn: boolean
  @column()
  declare defaultShowVatColumn: boolean
  @column()
  declare defaultSignatureField: boolean | null
  @column()
  declare defaultSubject: string | null
  @column()
  declare defaultVatExempt: boolean | null
  @column()
  declare defaultVatRate: number
  @column()
  declare documentFont: string | null
  @column()
  declare eInvoicingEnabled: boolean | null
  @column()
  declare footerMode: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare invoiceFilenamePattern: string | null
  @column()
  declare invoiceNumberPattern: string | null
  @column()
  declare logoBorderRadius: number
  @column()
  declare logoSource: string | null
  @column()
  declare logoUrl: string | null
  @column()
  declare nextCreditNoteNumber: string | null
  @column()
  declare nextInvoiceNumber: string | null
  @column()
  declare nextQuoteNumber: string | null
  @column()
  declare paymentMethods: any
  @column()
  declare pdpApiKey: string | null
  @column()
  declare pdpProvider: string | null
  @column()
  declare pdpSandbox: boolean | null
  @column()
  declare quoteFilenamePattern: string | null
  @column()
  declare quoteNumberPattern: string | null
  @column()
  declare stripePublishableKey: string | null
  @column()
  declare stripeSecretKey: string | null
  @column()
  declare stripeWebhookSecret: string | null
  @column()
  declare stripeWebhookSecretApp: string | null
  @column()
  declare teamId: string
  @column()
  declare template: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InvoiceSchema extends BaseModel {
  static $columns = ['accentColor', 'acceptanceConditions', 'bankAccountId', 'billingType', 'clientId', 'clientSiren', 'clientSnapshot', 'clientVatNumber', 'comment', 'companySnapshot', 'createdAt', 'deliveryAddress', 'documentTitle', 'dueDate', 'freeField', 'globalDiscountType', 'globalDiscountValue', 'id', 'invoiceNumber', 'issueDate', 'language', 'logoUrl', 'notes', 'operationCategory', 'paidDate', 'paymentMethod', 'paymentTerms', 'showQuantityColumn', 'showUnitColumn', 'showUnitPriceColumn', 'showVatColumn', 'signatureField', 'sourceQuoteId', 'status', 'subject', 'subtotal', 'taxAmount', 'teamId', 'total', 'updatedAt', 'vatExemptReason'] as const
  $columns = InvoiceSchema.$columns
  @column()
  declare accentColor: string
  @column()
  declare acceptanceConditions: string | null
  @column()
  declare bankAccountId: string | null
  @column()
  declare billingType: string
  @column()
  declare clientId: string | null
  @column()
  declare clientSiren: string | null
  @column()
  declare clientSnapshot: string | null
  @column()
  declare clientVatNumber: string | null
  @column()
  declare comment: string | null
  @column()
  declare companySnapshot: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deliveryAddress: string | null
  @column()
  declare documentTitle: string | null
  @column.date()
  declare dueDate: DateTime | null
  @column()
  declare freeField: string | null
  @column()
  declare globalDiscountType: string
  @column()
  declare globalDiscountValue: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare invoiceNumber: string
  @column.date()
  declare issueDate: DateTime
  @column()
  declare language: string
  @column()
  declare logoUrl: string | null
  @column()
  declare notes: string | null
  @column()
  declare operationCategory: string | null
  @column.date()
  declare paidDate: DateTime | null
  @column()
  declare paymentMethod: string | null
  @column()
  declare paymentTerms: string | null
  @column()
  declare showQuantityColumn: boolean
  @column()
  declare showUnitColumn: boolean
  @column()
  declare showUnitPriceColumn: boolean
  @column()
  declare showVatColumn: boolean
  @column()
  declare signatureField: boolean
  @column()
  declare sourceQuoteId: string | null
  @column()
  declare status: string
  @column()
  declare subject: string | null
  @column()
  declare subtotal: string
  @column()
  declare taxAmount: string
  @column()
  declare teamId: string
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vatExemptReason: string
}

export class LoginHistorySchema extends BaseModel {
  static $columns = ['city', 'country', 'createdAt', 'failureReason', 'id', 'ipAddress', 'isSuspicious', 'status', 'tokenIdentifier', 'userAgent', 'userId'] as const
  $columns = LoginHistorySchema.$columns
  @column()
  declare city: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare failureReason: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string
  @column()
  declare isSuspicious: boolean | null
  @column()
  declare status: string
  @column()
  declare tokenIdentifier: string | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string | null
}

export class OauthAppSchema extends BaseModel {
  static $columns = ['allowAllOrigins', 'allowedOrigins', 'clientId', 'clientSecretHash', 'createdAt', 'createdByUserId', 'description', 'encryptedWebhookSecret', 'iconUrl', 'id', 'isActive', 'isFirstParty', 'kind', 'name', 'redirectUris', 'scopes', 'updatedAt', 'webhookEvents', 'webhookUrl', 'websiteUrl'] as const
  $columns = OauthAppSchema.$columns
  @column()
  declare allowAllOrigins: boolean
  @column()
  declare allowedOrigins: any
  @column()
  declare clientId: string
  @column()
  declare clientSecretHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: string
  @column()
  declare description: string | null
  @column()
  declare encryptedWebhookSecret: string | null
  @column()
  declare iconUrl: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare isFirstParty: boolean
  @column()
  declare kind: string
  @column()
  declare name: string
  @column()
  declare redirectUris: any
  @column()
  declare scopes: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare webhookEvents: any | null
  @column()
  declare webhookUrl: string | null
  @column()
  declare websiteUrl: string | null
}

export class OauthAuthorizationSchema extends BaseModel {
  static $columns = ['createdAt', 'firstAuthorizedAt', 'id', 'lastAuthorizedAt', 'oauthAppId', 'scopes', 'updatedAt', 'userId'] as const
  $columns = OauthAuthorizationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare firstAuthorizedAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastAuthorizedAt: DateTime
  @column()
  declare oauthAppId: string
  @column()
  declare scopes: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class OauthCodeSchema extends BaseModel {
  static $columns = ['clientIp', 'codeChallenge', 'codeChallengeMethod', 'codeHash', 'createdAt', 'expiresAt', 'id', 'oauthAppId', 'redirectUri', 'scopes', 'usedAt', 'userAgent', 'userId'] as const
  $columns = OauthCodeSchema.$columns
  @column()
  declare clientIp: string | null
  @column()
  declare codeChallenge: string | null
  @column()
  declare codeChallengeMethod: string | null
  @column()
  declare codeHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare oauthAppId: string
  @column()
  declare redirectUri: string
  @column()
  declare scopes: any
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string
}

export class OauthTokenSchema extends BaseModel {
  static $columns = ['accessTokenHash', 'createdAt', 'deviceName', 'deviceOs', 'devicePlatform', 'expiresAt', 'id', 'lastIp', 'lastUsedAt', 'lastUserAgent', 'oauthAppId', 'refreshExpiresAt', 'refreshTokenHash', 'revokedAt', 'revokedReason', 'scopes', 'updatedAt', 'userId'] as const
  $columns = OauthTokenSchema.$columns
  @column()
  declare accessTokenHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceName: string | null
  @column()
  declare deviceOs: string | null
  @column()
  declare devicePlatform: string | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastIp: string | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare lastUserAgent: string | null
  @column()
  declare oauthAppId: string
  @column.dateTime()
  declare refreshExpiresAt: DateTime
  @column()
  declare refreshTokenHash: string
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare revokedReason: string | null
  @column()
  declare scopes: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class OauthWebhookDeliverySchema extends BaseModel {
  static $columns = ['attemptCount', 'createdAt', 'deliveredAt', 'encryptedPayload', 'eventId', 'eventType', 'id', 'lastError', 'lastStatusCode', 'nextAttemptAt', 'oauthAppId', 'status', 'updatedAt', 'url'] as const
  $columns = OauthWebhookDeliverySchema.$columns
  @column()
  declare attemptCount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare encryptedPayload: string
  @column()
  declare eventId: string
  @column()
  declare eventType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastError: string | null
  @column()
  declare lastStatusCode: number | null
  @column.dateTime()
  declare nextAttemptAt: DateTime | null
  @column()
  declare oauthAppId: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
}

export class PasskeyChallengeSchema extends BaseModel {
  static $columns = ['challenge', 'createdAt', 'expiresAt', 'id', 'type', 'userId'] as const
  $columns = PasskeyChallengeSchema.$columns
  @column()
  declare challenge: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare type: string
  @column()
  declare userId: string | null
}

export class PasskeyCredentialSchema extends BaseModel {
  static $columns = ['backedUp', 'counter', 'createdAt', 'credentialId', 'encryptedKek', 'friendlyName', 'id', 'lastUsedAt', 'publicKey', 'transports', 'updatedAt', 'userId'] as const
  $columns = PasskeyCredentialSchema.$columns
  @column()
  declare backedUp: boolean
  @column()
  declare counter: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare credentialId: string
  @column()
  declare encryptedKek: string | null
  @column()
  declare friendlyName: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare publicKey: string
  @column()
  declare transports: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class PaymentLinkSchema extends BaseModel {
  static $columns = ['amount', 'clientEmail', 'clientName', 'companyName', 'confirmationDate', 'confirmationNotes', 'confirmedAt', 'confirmedByUserId', 'createdAt', 'createdByUserId', 'currency', 'encryptedBankName', 'encryptedBic', 'encryptedIban', 'encryptedStripePublishableKey', 'encryptedStripeSecretKey', 'expirationType', 'expiresAt', 'id', 'invoiceId', 'invoiceNumber', 'isActive', 'paidAt', 'passwordHash', 'paymentMethod', 'paymentType', 'pdfData', 'pdfStorageKey', 'showIban', 'stripePaymentIntentId', 'stripeStatus', 'teamId', 'tokenHash', 'updatedAt'] as const
  $columns = PaymentLinkSchema.$columns
  @column()
  declare amount: string
  @column()
  declare clientEmail: string | null
  @column()
  declare clientName: string | null
  @column()
  declare companyName: string | null
  @column()
  declare confirmationDate: string | null
  @column()
  declare confirmationNotes: string | null
  @column.dateTime()
  declare confirmedAt: DateTime | null
  @column()
  declare confirmedByUserId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: string
  @column()
  declare currency: string
  @column()
  declare encryptedBankName: string | null
  @column()
  declare encryptedBic: string | null
  @column()
  declare encryptedIban: string | null
  @column()
  declare encryptedStripePublishableKey: string | null
  @column()
  declare encryptedStripeSecretKey: string | null
  @column()
  declare expirationType: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare invoiceId: string
  @column()
  declare invoiceNumber: string
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare paidAt: DateTime | null
  @column()
  declare passwordHash: string | null
  @column()
  declare paymentMethod: string
  @column()
  declare paymentType: string
  @column()
  declare pdfData: Buffer | null
  @column()
  declare pdfStorageKey: string | null
  @column()
  declare showIban: boolean
  @column()
  declare stripePaymentIntentId: string | null
  @column()
  declare stripeStatus: string | null
  @column()
  declare teamId: string
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PaymentReminderSettingSchema extends BaseModel {
  static $columns = ['autoSend', 'createdAt', 'daysAfterDue', 'daysBeforeDue', 'emailAccountId', 'emailBodyTemplate', 'emailSubjectTemplate', 'enabled', 'id', 'repeatIntervalDays', 'teamId', 'updatedAt'] as const
  $columns = PaymentReminderSettingSchema.$columns
  @column()
  declare autoSend: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare daysAfterDue: number | null
  @column()
  declare daysBeforeDue: number | null
  @column()
  declare emailAccountId: string | null
  @column()
  declare emailBodyTemplate: string | null
  @column()
  declare emailSubjectTemplate: string | null
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare repeatIntervalDays: number | null
  @column()
  declare teamId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PaymentReminderSchema extends BaseModel {
  static $columns = ['createdAt', 'errorMessage', 'id', 'invoiceId', 'sentAt', 'status', 'teamId', 'toEmail', 'type', 'updatedAt'] as const
  $columns = PaymentReminderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare invoiceId: string
  @column.dateTime()
  declare sentAt: DateTime
  @column()
  declare status: string
  @column()
  declare teamId: string
  @column()
  declare toEmail: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isArchived', 'name', 'reference', 'saleType', 'teamId', 'unit', 'unitPrice', 'updatedAt', 'vatRate'] as const
  $columns = ProductSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isArchived: boolean
  @column()
  declare name: string
  @column()
  declare reference: string | null
  @column()
  declare saleType: string | null
  @column()
  declare teamId: string
  @column()
  declare unit: string | null
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vatRate: string
}

export class QuoteLineSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'position', 'quantity', 'quoteId', 'saleType', 'total', 'unit', 'unitPrice', 'updatedAt', 'vatRate'] as const
  $columns = QuoteLineSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare position: number
  @column()
  declare quantity: string
  @column()
  declare quoteId: string
  @column()
  declare saleType: string | null
  @column()
  declare total: string
  @column()
  declare unit: string | null
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vatRate: string
}

export class QuoteSchema extends BaseModel {
  static $columns = ['accentColor', 'acceptanceConditions', 'billingType', 'clientId', 'clientSiren', 'clientSnapshot', 'clientVatNumber', 'comment', 'companySnapshot', 'createdAt', 'deliveryAddress', 'documentTitle', 'freeField', 'globalDiscountType', 'globalDiscountValue', 'id', 'issueDate', 'language', 'logoUrl', 'notes', 'quoteNumber', 'showQuantityColumn', 'showUnitColumn', 'showUnitPriceColumn', 'showVatColumn', 'signatureField', 'status', 'subject', 'subtotal', 'taxAmount', 'teamId', 'total', 'updatedAt', 'validityDate', 'vatExemptReason'] as const
  $columns = QuoteSchema.$columns
  @column()
  declare accentColor: string
  @column()
  declare acceptanceConditions: string | null
  @column()
  declare billingType: string
  @column()
  declare clientId: string | null
  @column()
  declare clientSiren: string | null
  @column()
  declare clientSnapshot: string | null
  @column()
  declare clientVatNumber: string | null
  @column()
  declare comment: string | null
  @column()
  declare companySnapshot: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deliveryAddress: string | null
  @column()
  declare documentTitle: string | null
  @column()
  declare freeField: string | null
  @column()
  declare globalDiscountType: string
  @column()
  declare globalDiscountValue: string
  @column({ isPrimary: true })
  declare id: string
  @column.date()
  declare issueDate: DateTime
  @column()
  declare language: string
  @column()
  declare logoUrl: string | null
  @column()
  declare notes: string | null
  @column()
  declare quoteNumber: string
  @column()
  declare showQuantityColumn: boolean
  @column()
  declare showUnitColumn: boolean
  @column()
  declare showUnitPriceColumn: boolean
  @column()
  declare showVatColumn: boolean
  @column()
  declare signatureField: boolean
  @column()
  declare status: string
  @column()
  declare subject: string | null
  @column()
  declare subtotal: string
  @column()
  declare taxAmount: string
  @column()
  declare teamId: string
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.date()
  declare validityDate: DateTime | null
  @column()
  declare vatExemptReason: string
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RecurringInvoiceLineSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'position', 'quantity', 'recurringInvoiceId', 'saleType', 'total', 'unit', 'unitPrice', 'updatedAt', 'vatRate'] as const
  $columns = RecurringInvoiceLineSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare position: number
  @column()
  declare quantity: string
  @column()
  declare recurringInvoiceId: string
  @column()
  declare saleType: string | null
  @column()
  declare total: string
  @column()
  declare unit: string | null
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vatRate: string
}

export class RecurringInvoiceSchema extends BaseModel {
  static $columns = ['accentColor', 'acceptanceConditions', 'bankAccountId', 'billingType', 'clientId', 'clientSiren', 'clientSnapshot', 'clientVatNumber', 'companySnapshot', 'createdAt', 'customIntervalDays', 'deliveryAddress', 'documentTitle', 'dueDays', 'endDate', 'freeField', 'frequency', 'generationCount', 'globalDiscountType', 'globalDiscountValue', 'id', 'isActive', 'language', 'lastGeneratedAt', 'logoUrl', 'name', 'nextExecutionDate', 'notes', 'operationCategory', 'paymentMethod', 'paymentTerms', 'signatureField', 'startDate', 'subject', 'teamId', 'updatedAt', 'vatExemptReason'] as const
  $columns = RecurringInvoiceSchema.$columns
  @column()
  declare accentColor: string
  @column()
  declare acceptanceConditions: string | null
  @column()
  declare bankAccountId: string | null
  @column()
  declare billingType: string
  @column()
  declare clientId: string | null
  @column()
  declare clientSiren: string | null
  @column()
  declare clientSnapshot: string | null
  @column()
  declare clientVatNumber: string | null
  @column()
  declare companySnapshot: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customIntervalDays: number | null
  @column()
  declare deliveryAddress: string | null
  @column()
  declare documentTitle: string | null
  @column()
  declare dueDays: number
  @column()
  declare endDate: string | null
  @column()
  declare freeField: string | null
  @column()
  declare frequency: string
  @column()
  declare generationCount: number
  @column()
  declare globalDiscountType: string
  @column()
  declare globalDiscountValue: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare language: string
  @column.dateTime()
  declare lastGeneratedAt: DateTime | null
  @column()
  declare logoUrl: string | null
  @column()
  declare name: string
  @column()
  declare nextExecutionDate: string
  @column()
  declare notes: string | null
  @column()
  declare operationCategory: string | null
  @column()
  declare paymentMethod: string | null
  @column()
  declare paymentTerms: string | null
  @column()
  declare signatureField: boolean
  @column()
  declare startDate: string
  @column()
  declare subject: string | null
  @column()
  declare teamId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vatExemptReason: string
}

export class TeamMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'dekVersion', 'encryptedInviteDek', 'encryptedTeamDek', 'encryptedTeamDekRecovery', 'id', 'invitationExpiresAt', 'invitationToken', 'invitedAt', 'invitedEmail', 'joinedAt', 'role', 'status', 'teamId', 'updatedAt', 'userId'] as const
  $columns = TeamMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dekVersion: number | null
  @column()
  declare encryptedInviteDek: string | null
  @column()
  declare encryptedTeamDek: string | null
  @column()
  declare encryptedTeamDekRecovery: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare invitationExpiresAt: DateTime | null
  @column()
  declare invitationToken: string | null
  @column.dateTime()
  declare invitedAt: DateTime | null
  @column()
  declare invitedEmail: string | null
  @column.dateTime()
  declare joinedAt: DateTime | null
  @column()
  declare role: string
  @column()
  declare status: string
  @column()
  declare teamId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class TeamSchema extends BaseModel {
  static $columns = ['b2BAccountId', 'createdAt', 'iconUrl', 'id', 'name', 'ownerId', 'updatedAt'] as const
  $columns = TeamSchema.$columns
  @column()
  declare b2BAccountId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare iconUrl: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare ownerId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'cryptoResetNeeded', 'currentTeamId', 'deletionCode', 'deletionCodeExpiresAt', 'deletionStartedAt', 'deletionStep', 'deletionToken', 'email', 'emailVerificationSentAt', 'emailVerificationToken', 'emailVerified', 'failedLoginAttempts', 'fullName', 'hasRecoveryKey', 'id', 'keyVersion', 'lastLoginAt', 'lockedUntil', 'oldSaltKdf', 'onboardingCompleted', 'password', 'passwordResetExpiresAt', 'passwordResetToken', 'pendingEmail', 'recoveryCodesEncrypted', 'recoveryKeyHash', 'saltKdf', 'securityCode', 'securityCodeExpiresAt', 'status', 'twoFactorEnabled', 'twoFactorSecretEncrypted', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cryptoResetNeeded: boolean
  @column()
  declare currentTeamId: string | null
  @column()
  declare deletionCode: string | null
  @column.dateTime()
  declare deletionCodeExpiresAt: DateTime | null
  @column.dateTime()
  declare deletionStartedAt: DateTime | null
  @column()
  declare deletionStep: number | null
  @column()
  declare deletionToken: string | null
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerificationSentAt: DateTime | null
  @column()
  declare emailVerificationToken: string | null
  @column()
  declare emailVerified: boolean | null
  @column()
  declare failedLoginAttempts: number | null
  @column()
  declare fullName: string | null
  @column()
  declare hasRecoveryKey: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare keyVersion: number | null
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column.dateTime()
  declare lockedUntil: DateTime | null
  @column()
  declare oldSaltKdf: string | null
  @column()
  declare onboardingCompleted: boolean
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime()
  declare passwordResetExpiresAt: DateTime | null
  @column()
  declare passwordResetToken: string | null
  @column()
  declare pendingEmail: string | null
  @column()
  declare recoveryCodesEncrypted: string | null
  @column()
  declare recoveryKeyHash: string | null
  @column()
  declare saltKdf: string | null
  @column()
  declare securityCode: string | null
  @column.dateTime()
  declare securityCodeExpiresAt: DateTime | null
  @column()
  declare status: string | null
  @column()
  declare twoFactorEnabled: boolean | null
  @column()
  declare twoFactorSecretEncrypted: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
