/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'id', 'ipAddress', 'metadata', 'resourceId', 'resourceType', 'severity', 'userAgent', 'userId'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: any | null
  @column()
  declare resourceId: string | null
  @column()
  declare resourceType: string
  @column()
  declare severity: string
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClientSchema extends BaseModel {
  static $columns = ['address', 'addressComplement', 'city', 'companyName', 'country', 'createdAt', 'email', 'firstName', 'id', 'includeInEmails', 'lastName', 'notes', 'phone', 'postalCode', 'siren', 'siret', 'teamId', 'type', 'updatedAt', 'vatNumber'] as const
  $columns = ClientSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare addressComplement: string | null
  @column()
  declare city: string | null
  @column()
  declare companyName: string | null
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare includeInEmails: boolean
  @column()
  declare lastName: string | null
  @column()
  declare notes: string | null
  @column()
  declare phone: string | null
  @column()
  declare postalCode: string | null
  @column()
  declare siren: string | null
  @column()
  declare siret: string | null
  @column()
  declare teamId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vatNumber: string | null
}

export class CompanySchema extends BaseModel {
  static $columns = ['addressLine1', 'addressLine2', 'bankName', 'bic', 'city', 'country', 'createdAt', 'currency', 'email', 'iban', 'id', 'legalForm', 'legalName', 'logoUrl', 'paymentConditions', 'phone', 'postalCode', 'siren', 'siret', 'teamId', 'tradeName', 'updatedAt', 'vatNumber', 'website'] as const
  $columns = CompanySchema.$columns
  @column()
  declare addressLine1: string | null
  @column()
  declare addressLine2: string | null
  @column()
  declare bankName: string | null
  @column()
  declare bic: string | null
  @column()
  declare city: string | null
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare email: string | null
  @column()
  declare iban: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare legalForm: string | null
  @column()
  declare legalName: string
  @column()
  declare logoUrl: string | null
  @column()
  declare paymentConditions: string | null
  @column()
  declare phone: string | null
  @column()
  declare postalCode: string | null
  @column()
  declare siren: string | null
  @column()
  declare siret: string | null
  @column()
  declare teamId: string
  @column()
  declare tradeName: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vatNumber: string | null
  @column()
  declare website: string | null
}

export class InvoiceSettingSchema extends BaseModel {
  static $columns = ['accentColor', 'billingType', 'createdAt', 'customPaymentMethod', 'darkMode', 'documentFont', 'id', 'logoUrl', 'paymentMethods', 'teamId', 'template', 'updatedAt'] as const
  $columns = InvoiceSettingSchema.$columns
  @column()
  declare accentColor: string
  @column()
  declare billingType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customPaymentMethod: string | null
  @column()
  declare darkMode: boolean
  @column()
  declare documentFont: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare logoUrl: string | null
  @column()
  declare paymentMethods: any
  @column()
  declare teamId: string
  @column()
  declare template: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LoginHistorySchema extends BaseModel {
  static $columns = ['city', 'country', 'createdAt', 'failureReason', 'id', 'ipAddress', 'isSuspicious', 'status', 'tokenIdentifier', 'userAgent', 'userId'] as const
  $columns = LoginHistorySchema.$columns
  @column()
  declare city: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare failureReason: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string
  @column()
  declare isSuspicious: boolean | null
  @column()
  declare status: string
  @column()
  declare tokenIdentifier: string | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string | null
}

export class QuoteLineSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'position', 'quantity', 'quoteId', 'saleType', 'total', 'unit', 'unitPrice', 'updatedAt', 'vatRate'] as const
  $columns = QuoteLineSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare position: number
  @column()
  declare quantity: string
  @column()
  declare quoteId: string
  @column()
  declare saleType: string | null
  @column()
  declare total: string
  @column()
  declare unit: string | null
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vatRate: string
}

export class QuoteSchema extends BaseModel {
  static $columns = ['accentColor', 'acceptanceConditions', 'billingType', 'clientId', 'clientSiren', 'clientVatNumber', 'createdAt', 'deliveryAddress', 'documentTitle', 'freeField', 'globalDiscountType', 'globalDiscountValue', 'id', 'issueDate', 'language', 'logoUrl', 'notes', 'quoteNumber', 'signatureField', 'status', 'subject', 'subtotal', 'taxAmount', 'teamId', 'total', 'updatedAt', 'validityDate'] as const
  $columns = QuoteSchema.$columns
  @column()
  declare accentColor: string
  @column()
  declare acceptanceConditions: string | null
  @column()
  declare billingType: string
  @column()
  declare clientId: string | null
  @column()
  declare clientSiren: string | null
  @column()
  declare clientVatNumber: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deliveryAddress: string | null
  @column()
  declare documentTitle: string | null
  @column()
  declare freeField: string | null
  @column()
  declare globalDiscountType: string
  @column()
  declare globalDiscountValue: string
  @column({ isPrimary: true })
  declare id: string
  @column.date()
  declare issueDate: DateTime
  @column()
  declare language: string
  @column()
  declare logoUrl: string | null
  @column()
  declare notes: string | null
  @column()
  declare quoteNumber: string
  @column()
  declare signatureField: boolean
  @column()
  declare status: string
  @column()
  declare subject: string | null
  @column()
  declare subtotal: string
  @column()
  declare taxAmount: string
  @column()
  declare teamId: string
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.date()
  declare validityDate: DateTime | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class TeamMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'invitationToken', 'invitedAt', 'invitedEmail', 'joinedAt', 'role', 'status', 'teamId', 'updatedAt', 'userId'] as const
  $columns = TeamMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare invitationToken: string | null
  @column.dateTime()
  declare invitedAt: DateTime | null
  @column()
  declare invitedEmail: string | null
  @column.dateTime()
  declare joinedAt: DateTime | null
  @column()
  declare role: string
  @column()
  declare status: string
  @column()
  declare teamId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class TeamSchema extends BaseModel {
  static $columns = ['createdAt', 'iconUrl', 'id', 'name', 'ownerId', 'updatedAt'] as const
  $columns = TeamSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare iconUrl: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare ownerId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'currentTeamId', 'email', 'emailVerificationSentAt', 'emailVerificationToken', 'emailVerified', 'failedLoginAttempts', 'fullName', 'id', 'lastLoginAt', 'lockedUntil', 'onboardingCompleted', 'password', 'passwordResetExpiresAt', 'passwordResetToken', 'recoveryCodesEncrypted', 'securityCode', 'securityCodeExpiresAt', 'status', 'twoFactorEnabled', 'twoFactorSecretEncrypted', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentTeamId: string | null
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerificationSentAt: DateTime | null
  @column()
  declare emailVerificationToken: string | null
  @column()
  declare emailVerified: boolean | null
  @column()
  declare failedLoginAttempts: number | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column.dateTime()
  declare lockedUntil: DateTime | null
  @column()
  declare onboardingCompleted: boolean
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime()
  declare passwordResetExpiresAt: DateTime | null
  @column()
  declare passwordResetToken: string | null
  @column()
  declare recoveryCodesEncrypted: string | null
  @column()
  declare securityCode: string | null
  @column.dateTime()
  declare securityCodeExpiresAt: DateTime | null
  @column()
  declare status: string | null
  @column()
  declare twoFactorEnabled: boolean | null
  @column()
  declare twoFactorSecretEncrypted: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
