/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type AuthProviderTransformer from '#transformers/auth_provider_transformer'
import type BankAccountTransformer from '#transformers/bank_account_transformer'
import type ClientContactTransformer from '#transformers/client_contact_transformer'
import type ClientTransformer from '#transformers/client_transformer'
import type CompanyTransformer from '#transformers/company_transformer'
import type CreditNoteLineTransformer from '#transformers/credit_note_line_transformer'
import type CreditNoteTransformer from '#transformers/credit_note_transformer'
import type EmailAccountTransformer from '#transformers/email_account_transformer'
import type EmailLogTransformer from '#transformers/email_log_transformer'
import type ExpenseCategoryTransformer from '#transformers/expense_category_transformer'
import type ExpenseTransformer from '#transformers/expense_transformer'
import type InvoiceLineTransformer from '#transformers/invoice_line_transformer'
import type InvoicePaymentTransformer from '#transformers/invoice_payment_transformer'
import type InvoiceTransformer from '#transformers/invoice_transformer'
import type LoginHistoryTransformer from '#transformers/login_history_transformer'
import type PaymentReminderTransformer from '#transformers/payment_reminder_transformer'
import type ProductTransformer from '#transformers/product_transformer'
import type QuoteLineTransformer from '#transformers/quote_line_transformer'
import type QuoteTransformer from '#transformers/quote_transformer'
import type RecurringInvoiceLineTransformer from '#transformers/recurring_invoice_line_transformer'
import type RecurringInvoiceTransformer from '#transformers/recurring_invoice_transformer'
import type TeamMemberTransformer from '#transformers/team_member_transformer'
import type TeamTransformer from '#transformers/team_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type AuthProvider = InferData<AuthProviderTransformer>
  export namespace AuthProvider {
    export type Variants = InferVariants<AuthProviderTransformer>
  }
  export type BankAccount = InferData<BankAccountTransformer>
  export namespace BankAccount {
    export type Variants = InferVariants<BankAccountTransformer>
  }
  export type ClientContact = InferData<ClientContactTransformer>
  export namespace ClientContact {
    export type Variants = InferVariants<ClientContactTransformer>
  }
  export type Client = InferData<ClientTransformer>
  export namespace Client {
    export type Variants = InferVariants<ClientTransformer>
  }
  export type Company = InferData<CompanyTransformer>
  export namespace Company {
    export type Variants = InferVariants<CompanyTransformer>
  }
  export type CreditNoteLine = InferData<CreditNoteLineTransformer>
  export namespace CreditNoteLine {
    export type Variants = InferVariants<CreditNoteLineTransformer>
  }
  export type CreditNote = InferData<CreditNoteTransformer>
  export namespace CreditNote {
    export type Variants = InferVariants<CreditNoteTransformer>
  }
  export type EmailAccount = InferData<EmailAccountTransformer>
  export namespace EmailAccount {
    export type Variants = InferVariants<EmailAccountTransformer>
  }
  export type EmailLog = InferData<EmailLogTransformer>
  export namespace EmailLog {
    export type Variants = InferVariants<EmailLogTransformer>
  }
  export type ExpenseCategory = InferData<ExpenseCategoryTransformer>
  export namespace ExpenseCategory {
    export type Variants = InferVariants<ExpenseCategoryTransformer>
  }
  export type Expense = InferData<ExpenseTransformer>
  export namespace Expense {
    export type Variants = InferVariants<ExpenseTransformer>
  }
  export type InvoiceLine = InferData<InvoiceLineTransformer>
  export namespace InvoiceLine {
    export type Variants = InferVariants<InvoiceLineTransformer>
  }
  export type InvoicePayment = InferData<InvoicePaymentTransformer>
  export namespace InvoicePayment {
    export type Variants = InferVariants<InvoicePaymentTransformer>
  }
  export type Invoice = InferData<InvoiceTransformer>
  export namespace Invoice {
    export type Variants = InferVariants<InvoiceTransformer>
  }
  export type LoginHistory = InferData<LoginHistoryTransformer>
  export namespace LoginHistory {
    export type Variants = InferVariants<LoginHistoryTransformer>
  }
  export type PaymentReminder = InferData<PaymentReminderTransformer>
  export namespace PaymentReminder {
    export type Variants = InferVariants<PaymentReminderTransformer>
  }
  export type Product = InferData<ProductTransformer>
  export namespace Product {
    export type Variants = InferVariants<ProductTransformer>
  }
  export type QuoteLine = InferData<QuoteLineTransformer>
  export namespace QuoteLine {
    export type Variants = InferVariants<QuoteLineTransformer>
  }
  export type Quote = InferData<QuoteTransformer>
  export namespace Quote {
    export type Variants = InferVariants<QuoteTransformer>
  }
  export type RecurringInvoiceLine = InferData<RecurringInvoiceLineTransformer>
  export namespace RecurringInvoiceLine {
    export type Variants = InferVariants<RecurringInvoiceLineTransformer>
  }
  export type RecurringInvoice = InferData<RecurringInvoiceTransformer>
  export namespace RecurringInvoice {
    export type Variants = InferVariants<RecurringInvoiceTransformer>
  }
  export type TeamMember = InferData<TeamMemberTransformer>
  export namespace TeamMember {
    export type Variants = InferVariants<TeamMemberTransformer>
  }
  export type Team = InferData<TeamTransformer>
  export namespace Team {
    export type Variants = InferVariants<TeamTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
