/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'signup': {
    methods: ["POST"],
    pattern: '/api/v1/auth/sign-up',
    tokens: [{"old":"/api/v1/auth/sign-up","type":0,"val":"api","end":""},{"old":"/api/v1/auth/sign-up","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/sign-up","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/sign-up","type":0,"val":"sign-up","end":""}],
    types: placeholder as Registry['signup']['types'],
  },
  'verify_email': {
    methods: ["POST"],
    pattern: '/api/v1/auth/verify-email',
    tokens: [{"old":"/api/v1/auth/verify-email","type":0,"val":"api","end":""},{"old":"/api/v1/auth/verify-email","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/verify-email","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/verify-email","type":0,"val":"verify-email","end":""}],
    types: placeholder as Registry['verify_email']['types'],
  },
  'resend_verification': {
    methods: ["POST"],
    pattern: '/api/v1/auth/resend-verification',
    tokens: [{"old":"/api/v1/auth/resend-verification","type":0,"val":"api","end":""},{"old":"/api/v1/auth/resend-verification","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/resend-verification","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/resend-verification","type":0,"val":"resend-verification","end":""}],
    types: placeholder as Registry['resend_verification']['types'],
  },
  'login': {
    methods: ["POST"],
    pattern: '/api/v1/auth/login',
    tokens: [{"old":"/api/v1/auth/login","type":0,"val":"api","end":""},{"old":"/api/v1/auth/login","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/login","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['login']['types'],
  },
  'two_factor_verify': {
    methods: ["POST"],
    pattern: '/api/v1/auth/login/2fa',
    tokens: [{"old":"/api/v1/auth/login/2fa","type":0,"val":"api","end":""},{"old":"/api/v1/auth/login/2fa","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/login/2fa","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/login/2fa","type":0,"val":"login","end":""},{"old":"/api/v1/auth/login/2fa","type":0,"val":"2fa","end":""}],
    types: placeholder as Registry['two_factor_verify']['types'],
  },
  'password_reset_request': {
    methods: ["POST"],
    pattern: '/api/v1/auth/password/forgot',
    tokens: [{"old":"/api/v1/auth/password/forgot","type":0,"val":"api","end":""},{"old":"/api/v1/auth/password/forgot","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/password/forgot","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/password/forgot","type":0,"val":"password","end":""},{"old":"/api/v1/auth/password/forgot","type":0,"val":"forgot","end":""}],
    types: placeholder as Registry['password_reset_request']['types'],
  },
  'password_reset': {
    methods: ["POST"],
    pattern: '/api/v1/auth/password/reset',
    tokens: [{"old":"/api/v1/auth/password/reset","type":0,"val":"api","end":""},{"old":"/api/v1/auth/password/reset","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/password/reset","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/password/reset","type":0,"val":"password","end":""},{"old":"/api/v1/auth/password/reset","type":0,"val":"reset","end":""}],
    types: placeholder as Registry['password_reset']['types'],
  },
  'logout': {
    methods: ["POST"],
    pattern: '/api/v1/auth/logout',
    tokens: [{"old":"/api/v1/auth/logout","type":0,"val":"api","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['logout']['types'],
  },
  'me': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/auth/me',
    tokens: [{"old":"/api/v1/auth/me","type":0,"val":"api","end":""},{"old":"/api/v1/auth/me","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/me","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['me']['types'],
  },
  'serve_avatar': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/avatars/:filename',
    tokens: [{"old":"/api/v1/avatars/:filename","type":0,"val":"api","end":""},{"old":"/api/v1/avatars/:filename","type":0,"val":"v1","end":""},{"old":"/api/v1/avatars/:filename","type":0,"val":"avatars","end":""},{"old":"/api/v1/avatars/:filename","type":1,"val":"filename","end":""}],
    types: placeholder as Registry['serve_avatar']['types'],
  },
  'profile_show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/account/profile',
    tokens: [{"old":"/api/v1/account/profile","type":0,"val":"api","end":""},{"old":"/api/v1/account/profile","type":0,"val":"v1","end":""},{"old":"/api/v1/account/profile","type":0,"val":"account","end":""},{"old":"/api/v1/account/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['profile_show']['types'],
  },
  'profile_update': {
    methods: ["PUT"],
    pattern: '/api/v1/account/profile',
    tokens: [{"old":"/api/v1/account/profile","type":0,"val":"api","end":""},{"old":"/api/v1/account/profile","type":0,"val":"v1","end":""},{"old":"/api/v1/account/profile","type":0,"val":"account","end":""},{"old":"/api/v1/account/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['profile_update']['types'],
  },
  'password_change': {
    methods: ["PUT"],
    pattern: '/api/v1/account/password',
    tokens: [{"old":"/api/v1/account/password","type":0,"val":"api","end":""},{"old":"/api/v1/account/password","type":0,"val":"v1","end":""},{"old":"/api/v1/account/password","type":0,"val":"account","end":""},{"old":"/api/v1/account/password","type":0,"val":"password","end":""}],
    types: placeholder as Registry['password_change']['types'],
  },
  'upload_avatar': {
    methods: ["POST"],
    pattern: '/api/v1/account/avatar',
    tokens: [{"old":"/api/v1/account/avatar","type":0,"val":"api","end":""},{"old":"/api/v1/account/avatar","type":0,"val":"v1","end":""},{"old":"/api/v1/account/avatar","type":0,"val":"account","end":""},{"old":"/api/v1/account/avatar","type":0,"val":"avatar","end":""}],
    types: placeholder as Registry['upload_avatar']['types'],
  },
  'sessions_list': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/account/sessions',
    tokens: [{"old":"/api/v1/account/sessions","type":0,"val":"api","end":""},{"old":"/api/v1/account/sessions","type":0,"val":"v1","end":""},{"old":"/api/v1/account/sessions","type":0,"val":"account","end":""},{"old":"/api/v1/account/sessions","type":0,"val":"sessions","end":""}],
    types: placeholder as Registry['sessions_list']['types'],
  },
  'session_revoke': {
    methods: ["DELETE"],
    pattern: '/api/v1/account/sessions/:id',
    tokens: [{"old":"/api/v1/account/sessions/:id","type":0,"val":"api","end":""},{"old":"/api/v1/account/sessions/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/account/sessions/:id","type":0,"val":"account","end":""},{"old":"/api/v1/account/sessions/:id","type":0,"val":"sessions","end":""},{"old":"/api/v1/account/sessions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['session_revoke']['types'],
  },
  'account_delete': {
    methods: ["DELETE"],
    pattern: '/api/v1/account',
    tokens: [{"old":"/api/v1/account","type":0,"val":"api","end":""},{"old":"/api/v1/account","type":0,"val":"v1","end":""},{"old":"/api/v1/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['account_delete']['types'],
  },
  'two_factor_setup': {
    methods: ["POST"],
    pattern: '/api/v1/account/2fa/setup',
    tokens: [{"old":"/api/v1/account/2fa/setup","type":0,"val":"api","end":""},{"old":"/api/v1/account/2fa/setup","type":0,"val":"v1","end":""},{"old":"/api/v1/account/2fa/setup","type":0,"val":"account","end":""},{"old":"/api/v1/account/2fa/setup","type":0,"val":"2fa","end":""},{"old":"/api/v1/account/2fa/setup","type":0,"val":"setup","end":""}],
    types: placeholder as Registry['two_factor_setup']['types'],
  },
  'two_factor_enable': {
    methods: ["POST"],
    pattern: '/api/v1/account/2fa/enable',
    tokens: [{"old":"/api/v1/account/2fa/enable","type":0,"val":"api","end":""},{"old":"/api/v1/account/2fa/enable","type":0,"val":"v1","end":""},{"old":"/api/v1/account/2fa/enable","type":0,"val":"account","end":""},{"old":"/api/v1/account/2fa/enable","type":0,"val":"2fa","end":""},{"old":"/api/v1/account/2fa/enable","type":0,"val":"enable","end":""}],
    types: placeholder as Registry['two_factor_enable']['types'],
  },
  'two_factor_disable': {
    methods: ["POST"],
    pattern: '/api/v1/account/2fa/disable',
    tokens: [{"old":"/api/v1/account/2fa/disable","type":0,"val":"api","end":""},{"old":"/api/v1/account/2fa/disable","type":0,"val":"v1","end":""},{"old":"/api/v1/account/2fa/disable","type":0,"val":"account","end":""},{"old":"/api/v1/account/2fa/disable","type":0,"val":"2fa","end":""},{"old":"/api/v1/account/2fa/disable","type":0,"val":"disable","end":""}],
    types: placeholder as Registry['two_factor_disable']['types'],
  },
  'security_verify.send_code': {
    methods: ["POST"],
    pattern: '/api/v1/account/security/send-code',
    tokens: [{"old":"/api/v1/account/security/send-code","type":0,"val":"api","end":""},{"old":"/api/v1/account/security/send-code","type":0,"val":"v1","end":""},{"old":"/api/v1/account/security/send-code","type":0,"val":"account","end":""},{"old":"/api/v1/account/security/send-code","type":0,"val":"security","end":""},{"old":"/api/v1/account/security/send-code","type":0,"val":"send-code","end":""}],
    types: placeholder as Registry['security_verify.send_code']['types'],
  },
  'security_verify.verify': {
    methods: ["POST"],
    pattern: '/api/v1/account/security/verify',
    tokens: [{"old":"/api/v1/account/security/verify","type":0,"val":"api","end":""},{"old":"/api/v1/account/security/verify","type":0,"val":"v1","end":""},{"old":"/api/v1/account/security/verify","type":0,"val":"account","end":""},{"old":"/api/v1/account/security/verify","type":0,"val":"security","end":""},{"old":"/api/v1/account/security/verify","type":0,"val":"verify","end":""}],
    types: placeholder as Registry['security_verify.verify']['types'],
  },
  'email_request_change': {
    methods: ["POST"],
    pattern: '/api/v1/account/email/request-change',
    tokens: [{"old":"/api/v1/account/email/request-change","type":0,"val":"api","end":""},{"old":"/api/v1/account/email/request-change","type":0,"val":"v1","end":""},{"old":"/api/v1/account/email/request-change","type":0,"val":"account","end":""},{"old":"/api/v1/account/email/request-change","type":0,"val":"email","end":""},{"old":"/api/v1/account/email/request-change","type":0,"val":"request-change","end":""}],
    types: placeholder as Registry['email_request_change']['types'],
  },
  'email_confirm_change': {
    methods: ["POST"],
    pattern: '/api/v1/account/email/confirm-change',
    tokens: [{"old":"/api/v1/account/email/confirm-change","type":0,"val":"api","end":""},{"old":"/api/v1/account/email/confirm-change","type":0,"val":"v1","end":""},{"old":"/api/v1/account/email/confirm-change","type":0,"val":"account","end":""},{"old":"/api/v1/account/email/confirm-change","type":0,"val":"email","end":""},{"old":"/api/v1/account/email/confirm-change","type":0,"val":"confirm-change","end":""}],
    types: placeholder as Registry['email_confirm_change']['types'],
  },
  'create_team': {
    methods: ["POST"],
    pattern: '/api/v1/onboarding/team',
    tokens: [{"old":"/api/v1/onboarding/team","type":0,"val":"api","end":""},{"old":"/api/v1/onboarding/team","type":0,"val":"v1","end":""},{"old":"/api/v1/onboarding/team","type":0,"val":"onboarding","end":""},{"old":"/api/v1/onboarding/team","type":0,"val":"team","end":""}],
    types: placeholder as Registry['create_team']['types'],
  },
  'create_company': {
    methods: ["POST"],
    pattern: '/api/v1/onboarding/company',
    tokens: [{"old":"/api/v1/onboarding/company","type":0,"val":"api","end":""},{"old":"/api/v1/onboarding/company","type":0,"val":"v1","end":""},{"old":"/api/v1/onboarding/company","type":0,"val":"onboarding","end":""},{"old":"/api/v1/onboarding/company","type":0,"val":"company","end":""}],
    types: placeholder as Registry['create_company']['types'],
  },
  'skip_company': {
    methods: ["POST"],
    pattern: '/api/v1/onboarding/skip',
    tokens: [{"old":"/api/v1/onboarding/skip","type":0,"val":"api","end":""},{"old":"/api/v1/onboarding/skip","type":0,"val":"v1","end":""},{"old":"/api/v1/onboarding/skip","type":0,"val":"onboarding","end":""},{"old":"/api/v1/onboarding/skip","type":0,"val":"skip","end":""}],
    types: placeholder as Registry['skip_company']['types'],
  },
  'search_company': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/onboarding/company/search',
    tokens: [{"old":"/api/v1/onboarding/company/search","type":0,"val":"api","end":""},{"old":"/api/v1/onboarding/company/search","type":0,"val":"v1","end":""},{"old":"/api/v1/onboarding/company/search","type":0,"val":"onboarding","end":""},{"old":"/api/v1/onboarding/company/search","type":0,"val":"company","end":""},{"old":"/api/v1/onboarding/company/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['search_company']['types'],
  },
  'complete_personalization': {
    methods: ["POST"],
    pattern: '/api/v1/onboarding/personalization',
    tokens: [{"old":"/api/v1/onboarding/personalization","type":0,"val":"api","end":""},{"old":"/api/v1/onboarding/personalization","type":0,"val":"v1","end":""},{"old":"/api/v1/onboarding/personalization","type":0,"val":"onboarding","end":""},{"old":"/api/v1/onboarding/personalization","type":0,"val":"personalization","end":""}],
    types: placeholder as Registry['complete_personalization']['types'],
  },
  'dashboard.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/dashboard',
    tokens: [{"old":"/api/v1/dashboard","type":0,"val":"api","end":""},{"old":"/api/v1/dashboard","type":0,"val":"v1","end":""},{"old":"/api/v1/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['dashboard.index']['types'],
  },
  'dashboard.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/dashboard/stats',
    tokens: [{"old":"/api/v1/dashboard/stats","type":0,"val":"api","end":""},{"old":"/api/v1/dashboard/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/dashboard/stats","type":0,"val":"dashboard","end":""},{"old":"/api/v1/dashboard/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['dashboard.stats']['types'],
  },
  'dashboard.sidebarCounts': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/dashboard/sidebar-counts',
    tokens: [{"old":"/api/v1/dashboard/sidebar-counts","type":0,"val":"api","end":""},{"old":"/api/v1/dashboard/sidebar-counts","type":0,"val":"v1","end":""},{"old":"/api/v1/dashboard/sidebar-counts","type":0,"val":"dashboard","end":""},{"old":"/api/v1/dashboard/sidebar-counts","type":0,"val":"sidebar-counts","end":""}],
    types: placeholder as Registry['dashboard.sidebarCounts']['types'],
  },
  'dashboard.charts': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/dashboard/charts',
    tokens: [{"old":"/api/v1/dashboard/charts","type":0,"val":"api","end":""},{"old":"/api/v1/dashboard/charts","type":0,"val":"v1","end":""},{"old":"/api/v1/dashboard/charts","type":0,"val":"dashboard","end":""},{"old":"/api/v1/dashboard/charts","type":0,"val":"charts","end":""}],
    types: placeholder as Registry['dashboard.charts']['types'],
  },
  'dashboard.charts.revenue': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/dashboard/charts/revenue',
    tokens: [{"old":"/api/v1/dashboard/charts/revenue","type":0,"val":"api","end":""},{"old":"/api/v1/dashboard/charts/revenue","type":0,"val":"v1","end":""},{"old":"/api/v1/dashboard/charts/revenue","type":0,"val":"dashboard","end":""},{"old":"/api/v1/dashboard/charts/revenue","type":0,"val":"charts","end":""},{"old":"/api/v1/dashboard/charts/revenue","type":0,"val":"revenue","end":""}],
    types: placeholder as Registry['dashboard.charts.revenue']['types'],
  },
  'dashboard.charts.collected': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/dashboard/charts/collected',
    tokens: [{"old":"/api/v1/dashboard/charts/collected","type":0,"val":"api","end":""},{"old":"/api/v1/dashboard/charts/collected","type":0,"val":"v1","end":""},{"old":"/api/v1/dashboard/charts/collected","type":0,"val":"dashboard","end":""},{"old":"/api/v1/dashboard/charts/collected","type":0,"val":"charts","end":""},{"old":"/api/v1/dashboard/charts/collected","type":0,"val":"collected","end":""}],
    types: placeholder as Registry['dashboard.charts.collected']['types'],
  },
  'dashboard.charts.micro': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/dashboard/charts/micro-thresholds',
    tokens: [{"old":"/api/v1/dashboard/charts/micro-thresholds","type":0,"val":"api","end":""},{"old":"/api/v1/dashboard/charts/micro-thresholds","type":0,"val":"v1","end":""},{"old":"/api/v1/dashboard/charts/micro-thresholds","type":0,"val":"dashboard","end":""},{"old":"/api/v1/dashboard/charts/micro-thresholds","type":0,"val":"charts","end":""},{"old":"/api/v1/dashboard/charts/micro-thresholds","type":0,"val":"micro-thresholds","end":""}],
    types: placeholder as Registry['dashboard.charts.micro']['types'],
  },
  'serve_icon': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/team-icons/:filename',
    tokens: [{"old":"/api/v1/team-icons/:filename","type":0,"val":"api","end":""},{"old":"/api/v1/team-icons/:filename","type":0,"val":"v1","end":""},{"old":"/api/v1/team-icons/:filename","type":0,"val":"team-icons","end":""},{"old":"/api/v1/team-icons/:filename","type":1,"val":"filename","end":""}],
    types: placeholder as Registry['serve_icon']['types'],
  },
  'team_list': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/team/all',
    tokens: [{"old":"/api/v1/team/all","type":0,"val":"api","end":""},{"old":"/api/v1/team/all","type":0,"val":"v1","end":""},{"old":"/api/v1/team/all","type":0,"val":"team","end":""},{"old":"/api/v1/team/all","type":0,"val":"all","end":""}],
    types: placeholder as Registry['team_list']['types'],
  },
  'team_create': {
    methods: ["POST"],
    pattern: '/api/v1/team/create',
    tokens: [{"old":"/api/v1/team/create","type":0,"val":"api","end":""},{"old":"/api/v1/team/create","type":0,"val":"v1","end":""},{"old":"/api/v1/team/create","type":0,"val":"team","end":""},{"old":"/api/v1/team/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['team_create']['types'],
  },
  'team_show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/team',
    tokens: [{"old":"/api/v1/team","type":0,"val":"api","end":""},{"old":"/api/v1/team","type":0,"val":"v1","end":""},{"old":"/api/v1/team","type":0,"val":"team","end":""}],
    types: placeholder as Registry['team_show']['types'],
  },
  'team_update': {
    methods: ["PUT"],
    pattern: '/api/v1/team',
    tokens: [{"old":"/api/v1/team","type":0,"val":"api","end":""},{"old":"/api/v1/team","type":0,"val":"v1","end":""},{"old":"/api/v1/team","type":0,"val":"team","end":""}],
    types: placeholder as Registry['team_update']['types'],
  },
  'team_delete': {
    methods: ["DELETE"],
    pattern: '/api/v1/team',
    tokens: [{"old":"/api/v1/team","type":0,"val":"api","end":""},{"old":"/api/v1/team","type":0,"val":"v1","end":""},{"old":"/api/v1/team","type":0,"val":"team","end":""}],
    types: placeholder as Registry['team_delete']['types'],
  },
  'upload_icon': {
    methods: ["POST"],
    pattern: '/api/v1/team/icon',
    tokens: [{"old":"/api/v1/team/icon","type":0,"val":"api","end":""},{"old":"/api/v1/team/icon","type":0,"val":"v1","end":""},{"old":"/api/v1/team/icon","type":0,"val":"team","end":""},{"old":"/api/v1/team/icon","type":0,"val":"icon","end":""}],
    types: placeholder as Registry['upload_icon']['types'],
  },
  'team_switch': {
    methods: ["POST"],
    pattern: '/api/v1/team/switch',
    tokens: [{"old":"/api/v1/team/switch","type":0,"val":"api","end":""},{"old":"/api/v1/team/switch","type":0,"val":"v1","end":""},{"old":"/api/v1/team/switch","type":0,"val":"team","end":""},{"old":"/api/v1/team/switch","type":0,"val":"switch","end":""}],
    types: placeholder as Registry['team_switch']['types'],
  },
  'team_export': {
    methods: ["POST"],
    pattern: '/api/v1/team/export',
    tokens: [{"old":"/api/v1/team/export","type":0,"val":"api","end":""},{"old":"/api/v1/team/export","type":0,"val":"v1","end":""},{"old":"/api/v1/team/export","type":0,"val":"team","end":""},{"old":"/api/v1/team/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['team_export']['types'],
  },
  'team_import': {
    methods: ["POST"],
    pattern: '/api/v1/team/import',
    tokens: [{"old":"/api/v1/team/import","type":0,"val":"api","end":""},{"old":"/api/v1/team/import","type":0,"val":"v1","end":""},{"old":"/api/v1/team/import","type":0,"val":"team","end":""},{"old":"/api/v1/team/import","type":0,"val":"import","end":""}],
    types: placeholder as Registry['team_import']['types'],
  },
  'team_members': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/team/members',
    tokens: [{"old":"/api/v1/team/members","type":0,"val":"api","end":""},{"old":"/api/v1/team/members","type":0,"val":"v1","end":""},{"old":"/api/v1/team/members","type":0,"val":"team","end":""},{"old":"/api/v1/team/members","type":0,"val":"members","end":""}],
    types: placeholder as Registry['team_members']['types'],
  },
  'team_invite': {
    methods: ["POST"],
    pattern: '/api/v1/team/invite',
    tokens: [{"old":"/api/v1/team/invite","type":0,"val":"api","end":""},{"old":"/api/v1/team/invite","type":0,"val":"v1","end":""},{"old":"/api/v1/team/invite","type":0,"val":"team","end":""},{"old":"/api/v1/team/invite","type":0,"val":"invite","end":""}],
    types: placeholder as Registry['team_invite']['types'],
  },
  'accept_invite': {
    methods: ["POST"],
    pattern: '/api/v1/team/invite/accept',
    tokens: [{"old":"/api/v1/team/invite/accept","type":0,"val":"api","end":""},{"old":"/api/v1/team/invite/accept","type":0,"val":"v1","end":""},{"old":"/api/v1/team/invite/accept","type":0,"val":"team","end":""},{"old":"/api/v1/team/invite/accept","type":0,"val":"invite","end":""},{"old":"/api/v1/team/invite/accept","type":0,"val":"accept","end":""}],
    types: placeholder as Registry['accept_invite']['types'],
  },
  'revoke_invite': {
    methods: ["DELETE"],
    pattern: '/api/v1/team/invite/:id',
    tokens: [{"old":"/api/v1/team/invite/:id","type":0,"val":"api","end":""},{"old":"/api/v1/team/invite/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/team/invite/:id","type":0,"val":"team","end":""},{"old":"/api/v1/team/invite/:id","type":0,"val":"invite","end":""},{"old":"/api/v1/team/invite/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['revoke_invite']['types'],
  },
  'update_role': {
    methods: ["PUT"],
    pattern: '/api/v1/team/members/:id/role',
    tokens: [{"old":"/api/v1/team/members/:id/role","type":0,"val":"api","end":""},{"old":"/api/v1/team/members/:id/role","type":0,"val":"v1","end":""},{"old":"/api/v1/team/members/:id/role","type":0,"val":"team","end":""},{"old":"/api/v1/team/members/:id/role","type":0,"val":"members","end":""},{"old":"/api/v1/team/members/:id/role","type":1,"val":"id","end":""},{"old":"/api/v1/team/members/:id/role","type":0,"val":"role","end":""}],
    types: placeholder as Registry['update_role']['types'],
  },
  'remove_member': {
    methods: ["DELETE"],
    pattern: '/api/v1/team/members/:id',
    tokens: [{"old":"/api/v1/team/members/:id","type":0,"val":"api","end":""},{"old":"/api/v1/team/members/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/team/members/:id","type":0,"val":"team","end":""},{"old":"/api/v1/team/members/:id","type":0,"val":"members","end":""},{"old":"/api/v1/team/members/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['remove_member']['types'],
  },
  'transfer_ownership': {
    methods: ["POST"],
    pattern: '/api/v1/team/transfer-ownership',
    tokens: [{"old":"/api/v1/team/transfer-ownership","type":0,"val":"api","end":""},{"old":"/api/v1/team/transfer-ownership","type":0,"val":"v1","end":""},{"old":"/api/v1/team/transfer-ownership","type":0,"val":"team","end":""},{"old":"/api/v1/team/transfer-ownership","type":0,"val":"transfer-ownership","end":""}],
    types: placeholder as Registry['transfer_ownership']['types'],
  },
  'invite_info': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/invite/:token',
    tokens: [{"old":"/api/v1/invite/:token","type":0,"val":"api","end":""},{"old":"/api/v1/invite/:token","type":0,"val":"v1","end":""},{"old":"/api/v1/invite/:token","type":0,"val":"invite","end":""},{"old":"/api/v1/invite/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['invite_info']['types'],
  },
  'serve_logo': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/company-logos/:filename',
    tokens: [{"old":"/api/v1/company-logos/:filename","type":0,"val":"api","end":""},{"old":"/api/v1/company-logos/:filename","type":0,"val":"v1","end":""},{"old":"/api/v1/company-logos/:filename","type":0,"val":"company-logos","end":""},{"old":"/api/v1/company-logos/:filename","type":1,"val":"filename","end":""}],
    types: placeholder as Registry['serve_logo']['types'],
  },
  'company_show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/company',
    tokens: [{"old":"/api/v1/company","type":0,"val":"api","end":""},{"old":"/api/v1/company","type":0,"val":"v1","end":""},{"old":"/api/v1/company","type":0,"val":"company","end":""}],
    types: placeholder as Registry['company_show']['types'],
  },
  'company_update': {
    methods: ["PUT"],
    pattern: '/api/v1/company',
    tokens: [{"old":"/api/v1/company","type":0,"val":"api","end":""},{"old":"/api/v1/company","type":0,"val":"v1","end":""},{"old":"/api/v1/company","type":0,"val":"company","end":""}],
    types: placeholder as Registry['company_update']['types'],
  },
  'company_bank': {
    methods: ["PUT"],
    pattern: '/api/v1/company/bank',
    tokens: [{"old":"/api/v1/company/bank","type":0,"val":"api","end":""},{"old":"/api/v1/company/bank","type":0,"val":"v1","end":""},{"old":"/api/v1/company/bank","type":0,"val":"company","end":""},{"old":"/api/v1/company/bank","type":0,"val":"bank","end":""}],
    types: placeholder as Registry['company_bank']['types'],
  },
  'upload_logo': {
    methods: ["POST"],
    pattern: '/api/v1/company/logo',
    tokens: [{"old":"/api/v1/company/logo","type":0,"val":"api","end":""},{"old":"/api/v1/company/logo","type":0,"val":"v1","end":""},{"old":"/api/v1/company/logo","type":0,"val":"company","end":""},{"old":"/api/v1/company/logo","type":0,"val":"logo","end":""}],
    types: placeholder as Registry['upload_logo']['types'],
  },
  'bank_accounts.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/company/bank-accounts',
    tokens: [{"old":"/api/v1/company/bank-accounts","type":0,"val":"api","end":""},{"old":"/api/v1/company/bank-accounts","type":0,"val":"v1","end":""},{"old":"/api/v1/company/bank-accounts","type":0,"val":"company","end":""},{"old":"/api/v1/company/bank-accounts","type":0,"val":"bank-accounts","end":""}],
    types: placeholder as Registry['bank_accounts.index']['types'],
  },
  'bank_accounts.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/company/bank-accounts/:id',
    tokens: [{"old":"/api/v1/company/bank-accounts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/company/bank-accounts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/company/bank-accounts/:id","type":0,"val":"company","end":""},{"old":"/api/v1/company/bank-accounts/:id","type":0,"val":"bank-accounts","end":""},{"old":"/api/v1/company/bank-accounts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['bank_accounts.show']['types'],
  },
  'bank_accounts.store': {
    methods: ["POST"],
    pattern: '/api/v1/company/bank-accounts',
    tokens: [{"old":"/api/v1/company/bank-accounts","type":0,"val":"api","end":""},{"old":"/api/v1/company/bank-accounts","type":0,"val":"v1","end":""},{"old":"/api/v1/company/bank-accounts","type":0,"val":"company","end":""},{"old":"/api/v1/company/bank-accounts","type":0,"val":"bank-accounts","end":""}],
    types: placeholder as Registry['bank_accounts.store']['types'],
  },
  'bank_accounts.update': {
    methods: ["PUT"],
    pattern: '/api/v1/company/bank-accounts/:id',
    tokens: [{"old":"/api/v1/company/bank-accounts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/company/bank-accounts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/company/bank-accounts/:id","type":0,"val":"company","end":""},{"old":"/api/v1/company/bank-accounts/:id","type":0,"val":"bank-accounts","end":""},{"old":"/api/v1/company/bank-accounts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['bank_accounts.update']['types'],
  },
  'bank_accounts.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/company/bank-accounts/:id',
    tokens: [{"old":"/api/v1/company/bank-accounts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/company/bank-accounts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/company/bank-accounts/:id","type":0,"val":"company","end":""},{"old":"/api/v1/company/bank-accounts/:id","type":0,"val":"bank-accounts","end":""},{"old":"/api/v1/company/bank-accounts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['bank_accounts.destroy']['types'],
  },
  'search_siren': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/clients/search-siren',
    tokens: [{"old":"/api/v1/clients/search-siren","type":0,"val":"api","end":""},{"old":"/api/v1/clients/search-siren","type":0,"val":"v1","end":""},{"old":"/api/v1/clients/search-siren","type":0,"val":"clients","end":""},{"old":"/api/v1/clients/search-siren","type":0,"val":"search-siren","end":""}],
    types: placeholder as Registry['search_siren']['types'],
  },
  'client_list': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/clients',
    tokens: [{"old":"/api/v1/clients","type":0,"val":"api","end":""},{"old":"/api/v1/clients","type":0,"val":"v1","end":""},{"old":"/api/v1/clients","type":0,"val":"clients","end":""}],
    types: placeholder as Registry['client_list']['types'],
  },
  'client_show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/clients/:id',
    tokens: [{"old":"/api/v1/clients/:id","type":0,"val":"api","end":""},{"old":"/api/v1/clients/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/clients/:id","type":0,"val":"clients","end":""},{"old":"/api/v1/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['client_show']['types'],
  },
  'client_create': {
    methods: ["POST"],
    pattern: '/api/v1/clients',
    tokens: [{"old":"/api/v1/clients","type":0,"val":"api","end":""},{"old":"/api/v1/clients","type":0,"val":"v1","end":""},{"old":"/api/v1/clients","type":0,"val":"clients","end":""}],
    types: placeholder as Registry['client_create']['types'],
  },
  'client_update': {
    methods: ["PUT"],
    pattern: '/api/v1/clients/:id',
    tokens: [{"old":"/api/v1/clients/:id","type":0,"val":"api","end":""},{"old":"/api/v1/clients/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/clients/:id","type":0,"val":"clients","end":""},{"old":"/api/v1/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['client_update']['types'],
  },
  'client_delete': {
    methods: ["DELETE"],
    pattern: '/api/v1/clients/:id',
    tokens: [{"old":"/api/v1/clients/:id","type":0,"val":"api","end":""},{"old":"/api/v1/clients/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/clients/:id","type":0,"val":"clients","end":""},{"old":"/api/v1/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['client_delete']['types'],
  },
  'serve_invoice_logo': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/invoice-logos/:filename',
    tokens: [{"old":"/api/v1/invoice-logos/:filename","type":0,"val":"api","end":""},{"old":"/api/v1/invoice-logos/:filename","type":0,"val":"v1","end":""},{"old":"/api/v1/invoice-logos/:filename","type":0,"val":"invoice-logos","end":""},{"old":"/api/v1/invoice-logos/:filename","type":1,"val":"filename","end":""}],
    types: placeholder as Registry['serve_invoice_logo']['types'],
  },
  'invoice_settings_show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/settings/invoices',
    tokens: [{"old":"/api/v1/settings/invoices","type":0,"val":"api","end":""},{"old":"/api/v1/settings/invoices","type":0,"val":"v1","end":""},{"old":"/api/v1/settings/invoices","type":0,"val":"settings","end":""},{"old":"/api/v1/settings/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['invoice_settings_show']['types'],
  },
  'invoice_settings_update': {
    methods: ["PUT"],
    pattern: '/api/v1/settings/invoices',
    tokens: [{"old":"/api/v1/settings/invoices","type":0,"val":"api","end":""},{"old":"/api/v1/settings/invoices","type":0,"val":"v1","end":""},{"old":"/api/v1/settings/invoices","type":0,"val":"settings","end":""},{"old":"/api/v1/settings/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['invoice_settings_update']['types'],
  },
  'invoice_logo_upload': {
    methods: ["POST"],
    pattern: '/api/v1/settings/invoices/logo',
    tokens: [{"old":"/api/v1/settings/invoices/logo","type":0,"val":"api","end":""},{"old":"/api/v1/settings/invoices/logo","type":0,"val":"v1","end":""},{"old":"/api/v1/settings/invoices/logo","type":0,"val":"settings","end":""},{"old":"/api/v1/settings/invoices/logo","type":0,"val":"invoices","end":""},{"old":"/api/v1/settings/invoices/logo","type":0,"val":"logo","end":""}],
    types: placeholder as Registry['invoice_logo_upload']['types'],
  },
  'quote_next_number': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/quotes/next-number',
    tokens: [{"old":"/api/v1/quotes/next-number","type":0,"val":"api","end":""},{"old":"/api/v1/quotes/next-number","type":0,"val":"v1","end":""},{"old":"/api/v1/quotes/next-number","type":0,"val":"quotes","end":""},{"old":"/api/v1/quotes/next-number","type":0,"val":"next-number","end":""}],
    types: placeholder as Registry['quote_next_number']['types'],
  },
  'quote_document_count': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/quotes/document-count',
    tokens: [{"old":"/api/v1/quotes/document-count","type":0,"val":"api","end":""},{"old":"/api/v1/quotes/document-count","type":0,"val":"v1","end":""},{"old":"/api/v1/quotes/document-count","type":0,"val":"quotes","end":""},{"old":"/api/v1/quotes/document-count","type":0,"val":"document-count","end":""}],
    types: placeholder as Registry['quote_document_count']['types'],
  },
  'quote_set_next_number': {
    methods: ["POST"],
    pattern: '/api/v1/quotes/set-next-number',
    tokens: [{"old":"/api/v1/quotes/set-next-number","type":0,"val":"api","end":""},{"old":"/api/v1/quotes/set-next-number","type":0,"val":"v1","end":""},{"old":"/api/v1/quotes/set-next-number","type":0,"val":"quotes","end":""},{"old":"/api/v1/quotes/set-next-number","type":0,"val":"set-next-number","end":""}],
    types: placeholder as Registry['quote_set_next_number']['types'],
  },
  'quote_list': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/quotes',
    tokens: [{"old":"/api/v1/quotes","type":0,"val":"api","end":""},{"old":"/api/v1/quotes","type":0,"val":"v1","end":""},{"old":"/api/v1/quotes","type":0,"val":"quotes","end":""}],
    types: placeholder as Registry['quote_list']['types'],
  },
  'quote_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/quotes/:id/pdf',
    tokens: [{"old":"/api/v1/quotes/:id/pdf","type":0,"val":"api","end":""},{"old":"/api/v1/quotes/:id/pdf","type":0,"val":"v1","end":""},{"old":"/api/v1/quotes/:id/pdf","type":0,"val":"quotes","end":""},{"old":"/api/v1/quotes/:id/pdf","type":1,"val":"id","end":""},{"old":"/api/v1/quotes/:id/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['quote_pdf']['types'],
  },
  'quote_factur_xml': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/quotes/:id/facturx',
    tokens: [{"old":"/api/v1/quotes/:id/facturx","type":0,"val":"api","end":""},{"old":"/api/v1/quotes/:id/facturx","type":0,"val":"v1","end":""},{"old":"/api/v1/quotes/:id/facturx","type":0,"val":"quotes","end":""},{"old":"/api/v1/quotes/:id/facturx","type":1,"val":"id","end":""},{"old":"/api/v1/quotes/:id/facturx","type":0,"val":"facturx","end":""}],
    types: placeholder as Registry['quote_factur_xml']['types'],
  },
  'quote_show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/quotes/:id',
    tokens: [{"old":"/api/v1/quotes/:id","type":0,"val":"api","end":""},{"old":"/api/v1/quotes/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/quotes/:id","type":0,"val":"quotes","end":""},{"old":"/api/v1/quotes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['quote_show']['types'],
  },
  'quote_create': {
    methods: ["POST"],
    pattern: '/api/v1/quotes',
    tokens: [{"old":"/api/v1/quotes","type":0,"val":"api","end":""},{"old":"/api/v1/quotes","type":0,"val":"v1","end":""},{"old":"/api/v1/quotes","type":0,"val":"quotes","end":""}],
    types: placeholder as Registry['quote_create']['types'],
  },
  'quote_update_status': {
    methods: ["PATCH"],
    pattern: '/api/v1/quotes/:id/status',
    tokens: [{"old":"/api/v1/quotes/:id/status","type":0,"val":"api","end":""},{"old":"/api/v1/quotes/:id/status","type":0,"val":"v1","end":""},{"old":"/api/v1/quotes/:id/status","type":0,"val":"quotes","end":""},{"old":"/api/v1/quotes/:id/status","type":1,"val":"id","end":""},{"old":"/api/v1/quotes/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['quote_update_status']['types'],
  },
  'quote_update_comment': {
    methods: ["PATCH"],
    pattern: '/api/v1/quotes/:id/comment',
    tokens: [{"old":"/api/v1/quotes/:id/comment","type":0,"val":"api","end":""},{"old":"/api/v1/quotes/:id/comment","type":0,"val":"v1","end":""},{"old":"/api/v1/quotes/:id/comment","type":0,"val":"quotes","end":""},{"old":"/api/v1/quotes/:id/comment","type":1,"val":"id","end":""},{"old":"/api/v1/quotes/:id/comment","type":0,"val":"comment","end":""}],
    types: placeholder as Registry['quote_update_comment']['types'],
  },
  'quote_duplicate': {
    methods: ["POST"],
    pattern: '/api/v1/quotes/:id/duplicate',
    tokens: [{"old":"/api/v1/quotes/:id/duplicate","type":0,"val":"api","end":""},{"old":"/api/v1/quotes/:id/duplicate","type":0,"val":"v1","end":""},{"old":"/api/v1/quotes/:id/duplicate","type":0,"val":"quotes","end":""},{"old":"/api/v1/quotes/:id/duplicate","type":1,"val":"id","end":""},{"old":"/api/v1/quotes/:id/duplicate","type":0,"val":"duplicate","end":""}],
    types: placeholder as Registry['quote_duplicate']['types'],
  },
  'quote_update': {
    methods: ["PUT"],
    pattern: '/api/v1/quotes/:id',
    tokens: [{"old":"/api/v1/quotes/:id","type":0,"val":"api","end":""},{"old":"/api/v1/quotes/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/quotes/:id","type":0,"val":"quotes","end":""},{"old":"/api/v1/quotes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['quote_update']['types'],
  },
  'quote_delete': {
    methods: ["DELETE"],
    pattern: '/api/v1/quotes/:id',
    tokens: [{"old":"/api/v1/quotes/:id","type":0,"val":"api","end":""},{"old":"/api/v1/quotes/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/quotes/:id","type":0,"val":"quotes","end":""},{"old":"/api/v1/quotes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['quote_delete']['types'],
  },
  'invoice_next_number': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/invoices/next-number',
    tokens: [{"old":"/api/v1/invoices/next-number","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/next-number","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/next-number","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/next-number","type":0,"val":"next-number","end":""}],
    types: placeholder as Registry['invoice_next_number']['types'],
  },
  'invoice_document_count': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/invoices/document-count',
    tokens: [{"old":"/api/v1/invoices/document-count","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/document-count","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/document-count","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/document-count","type":0,"val":"document-count","end":""}],
    types: placeholder as Registry['invoice_document_count']['types'],
  },
  'invoice_set_next_number': {
    methods: ["POST"],
    pattern: '/api/v1/invoices/set-next-number',
    tokens: [{"old":"/api/v1/invoices/set-next-number","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/set-next-number","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/set-next-number","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/set-next-number","type":0,"val":"set-next-number","end":""}],
    types: placeholder as Registry['invoice_set_next_number']['types'],
  },
  'invoice_list': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/invoices',
    tokens: [{"old":"/api/v1/invoices","type":0,"val":"api","end":""},{"old":"/api/v1/invoices","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['invoice_list']['types'],
  },
  'invoice_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/invoices/:id/pdf',
    tokens: [{"old":"/api/v1/invoices/:id/pdf","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/:id/pdf","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/:id/pdf","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/:id/pdf","type":1,"val":"id","end":""},{"old":"/api/v1/invoices/:id/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['invoice_pdf']['types'],
  },
  'invoice_show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/invoices/:id',
    tokens: [{"old":"/api/v1/invoices/:id","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/:id","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['invoice_show']['types'],
  },
  'invoice_create': {
    methods: ["POST"],
    pattern: '/api/v1/invoices',
    tokens: [{"old":"/api/v1/invoices","type":0,"val":"api","end":""},{"old":"/api/v1/invoices","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['invoice_create']['types'],
  },
  'invoice_convert_quote': {
    methods: ["POST"],
    pattern: '/api/v1/invoices/convert-quote/:id',
    tokens: [{"old":"/api/v1/invoices/convert-quote/:id","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/convert-quote/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/convert-quote/:id","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/convert-quote/:id","type":0,"val":"convert-quote","end":""},{"old":"/api/v1/invoices/convert-quote/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['invoice_convert_quote']['types'],
  },
  'invoice_update_status': {
    methods: ["PATCH"],
    pattern: '/api/v1/invoices/:id/status',
    tokens: [{"old":"/api/v1/invoices/:id/status","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/:id/status","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/:id/status","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/:id/status","type":1,"val":"id","end":""},{"old":"/api/v1/invoices/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['invoice_update_status']['types'],
  },
  'invoice_unlink_quote': {
    methods: ["PATCH"],
    pattern: '/api/v1/invoices/:id/unlink-quote',
    tokens: [{"old":"/api/v1/invoices/:id/unlink-quote","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/:id/unlink-quote","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/:id/unlink-quote","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/:id/unlink-quote","type":1,"val":"id","end":""},{"old":"/api/v1/invoices/:id/unlink-quote","type":0,"val":"unlink-quote","end":""}],
    types: placeholder as Registry['invoice_unlink_quote']['types'],
  },
  'invoice_update_comment': {
    methods: ["PATCH"],
    pattern: '/api/v1/invoices/:id/comment',
    tokens: [{"old":"/api/v1/invoices/:id/comment","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/:id/comment","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/:id/comment","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/:id/comment","type":1,"val":"id","end":""},{"old":"/api/v1/invoices/:id/comment","type":0,"val":"comment","end":""}],
    types: placeholder as Registry['invoice_update_comment']['types'],
  },
  'invoice_duplicate': {
    methods: ["POST"],
    pattern: '/api/v1/invoices/:id/duplicate',
    tokens: [{"old":"/api/v1/invoices/:id/duplicate","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/:id/duplicate","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/:id/duplicate","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/:id/duplicate","type":1,"val":"id","end":""},{"old":"/api/v1/invoices/:id/duplicate","type":0,"val":"duplicate","end":""}],
    types: placeholder as Registry['invoice_duplicate']['types'],
  },
  'invoice_update': {
    methods: ["PUT"],
    pattern: '/api/v1/invoices/:id',
    tokens: [{"old":"/api/v1/invoices/:id","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/:id","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['invoice_update']['types'],
  },
  'invoice_delete': {
    methods: ["DELETE"],
    pattern: '/api/v1/invoices/:id',
    tokens: [{"old":"/api/v1/invoices/:id","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/:id","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['invoice_delete']['types'],
  },
  'e_invoicing_submit': {
    methods: ["POST"],
    pattern: '/api/v1/einvoicing/submit/:id',
    tokens: [{"old":"/api/v1/einvoicing/submit/:id","type":0,"val":"api","end":""},{"old":"/api/v1/einvoicing/submit/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/einvoicing/submit/:id","type":0,"val":"einvoicing","end":""},{"old":"/api/v1/einvoicing/submit/:id","type":0,"val":"submit","end":""},{"old":"/api/v1/einvoicing/submit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['e_invoicing_submit']['types'],
  },
  'validate_connection': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/einvoicing/validate-connection',
    tokens: [{"old":"/api/v1/einvoicing/validate-connection","type":0,"val":"api","end":""},{"old":"/api/v1/einvoicing/validate-connection","type":0,"val":"v1","end":""},{"old":"/api/v1/einvoicing/validate-connection","type":0,"val":"einvoicing","end":""},{"old":"/api/v1/einvoicing/validate-connection","type":0,"val":"validate-connection","end":""}],
    types: placeholder as Registry['validate_connection']['types'],
  },
  'gmail_callback': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/email/oauth/gmail/callback',
    tokens: [{"old":"/api/v1/email/oauth/gmail/callback","type":0,"val":"api","end":""},{"old":"/api/v1/email/oauth/gmail/callback","type":0,"val":"v1","end":""},{"old":"/api/v1/email/oauth/gmail/callback","type":0,"val":"email","end":""},{"old":"/api/v1/email/oauth/gmail/callback","type":0,"val":"oauth","end":""},{"old":"/api/v1/email/oauth/gmail/callback","type":0,"val":"gmail","end":""},{"old":"/api/v1/email/oauth/gmail/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['gmail_callback']['types'],
  },
  'email_accounts_list': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/email/accounts',
    tokens: [{"old":"/api/v1/email/accounts","type":0,"val":"api","end":""},{"old":"/api/v1/email/accounts","type":0,"val":"v1","end":""},{"old":"/api/v1/email/accounts","type":0,"val":"email","end":""},{"old":"/api/v1/email/accounts","type":0,"val":"accounts","end":""}],
    types: placeholder as Registry['email_accounts_list']['types'],
  },
  'email_accounts_delete': {
    methods: ["DELETE"],
    pattern: '/api/v1/email/accounts/:id',
    tokens: [{"old":"/api/v1/email/accounts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/email/accounts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/email/accounts/:id","type":0,"val":"email","end":""},{"old":"/api/v1/email/accounts/:id","type":0,"val":"accounts","end":""},{"old":"/api/v1/email/accounts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['email_accounts_delete']['types'],
  },
  'email_accounts_set_default': {
    methods: ["PATCH"],
    pattern: '/api/v1/email/accounts/:id/default',
    tokens: [{"old":"/api/v1/email/accounts/:id/default","type":0,"val":"api","end":""},{"old":"/api/v1/email/accounts/:id/default","type":0,"val":"v1","end":""},{"old":"/api/v1/email/accounts/:id/default","type":0,"val":"email","end":""},{"old":"/api/v1/email/accounts/:id/default","type":0,"val":"accounts","end":""},{"old":"/api/v1/email/accounts/:id/default","type":1,"val":"id","end":""},{"old":"/api/v1/email/accounts/:id/default","type":0,"val":"default","end":""}],
    types: placeholder as Registry['email_accounts_set_default']['types'],
  },
  'gmail_auth_url': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/email/oauth/gmail/url',
    tokens: [{"old":"/api/v1/email/oauth/gmail/url","type":0,"val":"api","end":""},{"old":"/api/v1/email/oauth/gmail/url","type":0,"val":"v1","end":""},{"old":"/api/v1/email/oauth/gmail/url","type":0,"val":"email","end":""},{"old":"/api/v1/email/oauth/gmail/url","type":0,"val":"oauth","end":""},{"old":"/api/v1/email/oauth/gmail/url","type":0,"val":"gmail","end":""},{"old":"/api/v1/email/oauth/gmail/url","type":0,"val":"url","end":""}],
    types: placeholder as Registry['gmail_auth_url']['types'],
  },
  'send_email': {
    methods: ["POST"],
    pattern: '/api/v1/email/send',
    tokens: [{"old":"/api/v1/email/send","type":0,"val":"api","end":""},{"old":"/api/v1/email/send","type":0,"val":"v1","end":""},{"old":"/api/v1/email/send","type":0,"val":"email","end":""},{"old":"/api/v1/email/send","type":0,"val":"send","end":""}],
    types: placeholder as Registry['send_email']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
