/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'signup': {
    methods: ["POST"],
    pattern: '/auth/sign-up',
    tokens: [{"old":"/auth/sign-up","type":0,"val":"auth","end":""},{"old":"/auth/sign-up","type":0,"val":"sign-up","end":""}],
    types: placeholder as Registry['signup']['types'],
  },
  'verify_email': {
    methods: ["POST"],
    pattern: '/auth/verify-email',
    tokens: [{"old":"/auth/verify-email","type":0,"val":"auth","end":""},{"old":"/auth/verify-email","type":0,"val":"verify-email","end":""}],
    types: placeholder as Registry['verify_email']['types'],
  },
  'resend_verification': {
    methods: ["POST"],
    pattern: '/auth/resend-verification',
    tokens: [{"old":"/auth/resend-verification","type":0,"val":"auth","end":""},{"old":"/auth/resend-verification","type":0,"val":"resend-verification","end":""}],
    types: placeholder as Registry['resend_verification']['types'],
  },
  'login': {
    methods: ["POST"],
    pattern: '/auth/login',
    tokens: [{"old":"/auth/login","type":0,"val":"auth","end":""},{"old":"/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['login']['types'],
  },
  'two_factor_verify': {
    methods: ["POST"],
    pattern: '/auth/login/2fa',
    tokens: [{"old":"/auth/login/2fa","type":0,"val":"auth","end":""},{"old":"/auth/login/2fa","type":0,"val":"login","end":""},{"old":"/auth/login/2fa","type":0,"val":"2fa","end":""}],
    types: placeholder as Registry['two_factor_verify']['types'],
  },
  'password_reset_request': {
    methods: ["POST"],
    pattern: '/auth/password/forgot',
    tokens: [{"old":"/auth/password/forgot","type":0,"val":"auth","end":""},{"old":"/auth/password/forgot","type":0,"val":"password","end":""},{"old":"/auth/password/forgot","type":0,"val":"forgot","end":""}],
    types: placeholder as Registry['password_reset_request']['types'],
  },
  'password_reset': {
    methods: ["POST"],
    pattern: '/auth/password/reset',
    tokens: [{"old":"/auth/password/reset","type":0,"val":"auth","end":""},{"old":"/auth/password/reset","type":0,"val":"password","end":""},{"old":"/auth/password/reset","type":0,"val":"reset","end":""}],
    types: placeholder as Registry['password_reset']['types'],
  },
  'logout': {
    methods: ["POST"],
    pattern: '/auth/logout',
    tokens: [{"old":"/auth/logout","type":0,"val":"auth","end":""},{"old":"/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['logout']['types'],
  },
  'me': {
    methods: ["GET","HEAD"],
    pattern: '/auth/me',
    tokens: [{"old":"/auth/me","type":0,"val":"auth","end":""},{"old":"/auth/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['me']['types'],
  },
  'serve_avatar': {
    methods: ["GET","HEAD"],
    pattern: '/avatars/:filename',
    tokens: [{"old":"/avatars/:filename","type":0,"val":"avatars","end":""},{"old":"/avatars/:filename","type":1,"val":"filename","end":""}],
    types: placeholder as Registry['serve_avatar']['types'],
  },
  'profile_show': {
    methods: ["GET","HEAD"],
    pattern: '/account/profile',
    tokens: [{"old":"/account/profile","type":0,"val":"account","end":""},{"old":"/account/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['profile_show']['types'],
  },
  'profile_update': {
    methods: ["PUT"],
    pattern: '/account/profile',
    tokens: [{"old":"/account/profile","type":0,"val":"account","end":""},{"old":"/account/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['profile_update']['types'],
  },
  'password_change': {
    methods: ["PUT"],
    pattern: '/account/password',
    tokens: [{"old":"/account/password","type":0,"val":"account","end":""},{"old":"/account/password","type":0,"val":"password","end":""}],
    types: placeholder as Registry['password_change']['types'],
  },
  'upload_avatar': {
    methods: ["POST"],
    pattern: '/account/avatar',
    tokens: [{"old":"/account/avatar","type":0,"val":"account","end":""},{"old":"/account/avatar","type":0,"val":"avatar","end":""}],
    types: placeholder as Registry['upload_avatar']['types'],
  },
  'sessions_list': {
    methods: ["GET","HEAD"],
    pattern: '/account/sessions',
    tokens: [{"old":"/account/sessions","type":0,"val":"account","end":""},{"old":"/account/sessions","type":0,"val":"sessions","end":""}],
    types: placeholder as Registry['sessions_list']['types'],
  },
  'session_revoke': {
    methods: ["DELETE"],
    pattern: '/account/sessions/:id',
    tokens: [{"old":"/account/sessions/:id","type":0,"val":"account","end":""},{"old":"/account/sessions/:id","type":0,"val":"sessions","end":""},{"old":"/account/sessions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['session_revoke']['types'],
  },
  'account_delete': {
    methods: ["DELETE"],
    pattern: '/account',
    tokens: [{"old":"/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['account_delete']['types'],
  },
  'two_factor_setup': {
    methods: ["POST"],
    pattern: '/account/2fa/setup',
    tokens: [{"old":"/account/2fa/setup","type":0,"val":"account","end":""},{"old":"/account/2fa/setup","type":0,"val":"2fa","end":""},{"old":"/account/2fa/setup","type":0,"val":"setup","end":""}],
    types: placeholder as Registry['two_factor_setup']['types'],
  },
  'two_factor_enable': {
    methods: ["POST"],
    pattern: '/account/2fa/enable',
    tokens: [{"old":"/account/2fa/enable","type":0,"val":"account","end":""},{"old":"/account/2fa/enable","type":0,"val":"2fa","end":""},{"old":"/account/2fa/enable","type":0,"val":"enable","end":""}],
    types: placeholder as Registry['two_factor_enable']['types'],
  },
  'two_factor_disable': {
    methods: ["POST"],
    pattern: '/account/2fa/disable',
    tokens: [{"old":"/account/2fa/disable","type":0,"val":"account","end":""},{"old":"/account/2fa/disable","type":0,"val":"2fa","end":""},{"old":"/account/2fa/disable","type":0,"val":"disable","end":""}],
    types: placeholder as Registry['two_factor_disable']['types'],
  },
  'security_verify.send_code': {
    methods: ["POST"],
    pattern: '/account/security/send-code',
    tokens: [{"old":"/account/security/send-code","type":0,"val":"account","end":""},{"old":"/account/security/send-code","type":0,"val":"security","end":""},{"old":"/account/security/send-code","type":0,"val":"send-code","end":""}],
    types: placeholder as Registry['security_verify.send_code']['types'],
  },
  'security_verify.verify': {
    methods: ["POST"],
    pattern: '/account/security/verify',
    tokens: [{"old":"/account/security/verify","type":0,"val":"account","end":""},{"old":"/account/security/verify","type":0,"val":"security","end":""},{"old":"/account/security/verify","type":0,"val":"verify","end":""}],
    types: placeholder as Registry['security_verify.verify']['types'],
  },
  'email_request_change': {
    methods: ["POST"],
    pattern: '/account/email/request-change',
    tokens: [{"old":"/account/email/request-change","type":0,"val":"account","end":""},{"old":"/account/email/request-change","type":0,"val":"email","end":""},{"old":"/account/email/request-change","type":0,"val":"request-change","end":""}],
    types: placeholder as Registry['email_request_change']['types'],
  },
  'email_confirm_change': {
    methods: ["POST"],
    pattern: '/account/email/confirm-change',
    tokens: [{"old":"/account/email/confirm-change","type":0,"val":"account","end":""},{"old":"/account/email/confirm-change","type":0,"val":"email","end":""},{"old":"/account/email/confirm-change","type":0,"val":"confirm-change","end":""}],
    types: placeholder as Registry['email_confirm_change']['types'],
  },
  'create_team': {
    methods: ["POST"],
    pattern: '/onboarding/team',
    tokens: [{"old":"/onboarding/team","type":0,"val":"onboarding","end":""},{"old":"/onboarding/team","type":0,"val":"team","end":""}],
    types: placeholder as Registry['create_team']['types'],
  },
  'create_company': {
    methods: ["POST"],
    pattern: '/onboarding/company',
    tokens: [{"old":"/onboarding/company","type":0,"val":"onboarding","end":""},{"old":"/onboarding/company","type":0,"val":"company","end":""}],
    types: placeholder as Registry['create_company']['types'],
  },
  'skip_company': {
    methods: ["POST"],
    pattern: '/onboarding/skip',
    tokens: [{"old":"/onboarding/skip","type":0,"val":"onboarding","end":""},{"old":"/onboarding/skip","type":0,"val":"skip","end":""}],
    types: placeholder as Registry['skip_company']['types'],
  },
  'search_company': {
    methods: ["GET","HEAD"],
    pattern: '/onboarding/company/search',
    tokens: [{"old":"/onboarding/company/search","type":0,"val":"onboarding","end":""},{"old":"/onboarding/company/search","type":0,"val":"company","end":""},{"old":"/onboarding/company/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['search_company']['types'],
  },
  'complete_personalization': {
    methods: ["POST"],
    pattern: '/onboarding/personalization',
    tokens: [{"old":"/onboarding/personalization","type":0,"val":"onboarding","end":""},{"old":"/onboarding/personalization","type":0,"val":"personalization","end":""}],
    types: placeholder as Registry['complete_personalization']['types'],
  },
  'dashboard.index': {
    methods: ["GET","HEAD"],
    pattern: '/dashboard',
    tokens: [{"old":"/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['dashboard.index']['types'],
  },
  'dashboard.stats': {
    methods: ["GET","HEAD"],
    pattern: '/dashboard/stats',
    tokens: [{"old":"/dashboard/stats","type":0,"val":"dashboard","end":""},{"old":"/dashboard/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['dashboard.stats']['types'],
  },
  'dashboard.sidebarCounts': {
    methods: ["GET","HEAD"],
    pattern: '/dashboard/sidebar-counts',
    tokens: [{"old":"/dashboard/sidebar-counts","type":0,"val":"dashboard","end":""},{"old":"/dashboard/sidebar-counts","type":0,"val":"sidebar-counts","end":""}],
    types: placeholder as Registry['dashboard.sidebarCounts']['types'],
  },
  'serve_icon': {
    methods: ["GET","HEAD"],
    pattern: '/team-icons/:filename',
    tokens: [{"old":"/team-icons/:filename","type":0,"val":"team-icons","end":""},{"old":"/team-icons/:filename","type":1,"val":"filename","end":""}],
    types: placeholder as Registry['serve_icon']['types'],
  },
  'team_list': {
    methods: ["GET","HEAD"],
    pattern: '/team/all',
    tokens: [{"old":"/team/all","type":0,"val":"team","end":""},{"old":"/team/all","type":0,"val":"all","end":""}],
    types: placeholder as Registry['team_list']['types'],
  },
  'team_create': {
    methods: ["POST"],
    pattern: '/team/create',
    tokens: [{"old":"/team/create","type":0,"val":"team","end":""},{"old":"/team/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['team_create']['types'],
  },
  'team_show': {
    methods: ["GET","HEAD"],
    pattern: '/team',
    tokens: [{"old":"/team","type":0,"val":"team","end":""}],
    types: placeholder as Registry['team_show']['types'],
  },
  'team_update': {
    methods: ["PUT"],
    pattern: '/team',
    tokens: [{"old":"/team","type":0,"val":"team","end":""}],
    types: placeholder as Registry['team_update']['types'],
  },
  'upload_icon': {
    methods: ["POST"],
    pattern: '/team/icon',
    tokens: [{"old":"/team/icon","type":0,"val":"team","end":""},{"old":"/team/icon","type":0,"val":"icon","end":""}],
    types: placeholder as Registry['upload_icon']['types'],
  },
  'team_switch': {
    methods: ["POST"],
    pattern: '/team/switch',
    tokens: [{"old":"/team/switch","type":0,"val":"team","end":""},{"old":"/team/switch","type":0,"val":"switch","end":""}],
    types: placeholder as Registry['team_switch']['types'],
  },
  'team_members': {
    methods: ["GET","HEAD"],
    pattern: '/team/members',
    tokens: [{"old":"/team/members","type":0,"val":"team","end":""},{"old":"/team/members","type":0,"val":"members","end":""}],
    types: placeholder as Registry['team_members']['types'],
  },
  'team_invite': {
    methods: ["POST"],
    pattern: '/team/invite',
    tokens: [{"old":"/team/invite","type":0,"val":"team","end":""},{"old":"/team/invite","type":0,"val":"invite","end":""}],
    types: placeholder as Registry['team_invite']['types'],
  },
  'accept_invite': {
    methods: ["POST"],
    pattern: '/team/invite/accept',
    tokens: [{"old":"/team/invite/accept","type":0,"val":"team","end":""},{"old":"/team/invite/accept","type":0,"val":"invite","end":""},{"old":"/team/invite/accept","type":0,"val":"accept","end":""}],
    types: placeholder as Registry['accept_invite']['types'],
  },
  'revoke_invite': {
    methods: ["DELETE"],
    pattern: '/team/invite/:id',
    tokens: [{"old":"/team/invite/:id","type":0,"val":"team","end":""},{"old":"/team/invite/:id","type":0,"val":"invite","end":""},{"old":"/team/invite/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['revoke_invite']['types'],
  },
  'update_role': {
    methods: ["PUT"],
    pattern: '/team/members/:id/role',
    tokens: [{"old":"/team/members/:id/role","type":0,"val":"team","end":""},{"old":"/team/members/:id/role","type":0,"val":"members","end":""},{"old":"/team/members/:id/role","type":1,"val":"id","end":""},{"old":"/team/members/:id/role","type":0,"val":"role","end":""}],
    types: placeholder as Registry['update_role']['types'],
  },
  'remove_member': {
    methods: ["DELETE"],
    pattern: '/team/members/:id',
    tokens: [{"old":"/team/members/:id","type":0,"val":"team","end":""},{"old":"/team/members/:id","type":0,"val":"members","end":""},{"old":"/team/members/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['remove_member']['types'],
  },
  'transfer_ownership': {
    methods: ["POST"],
    pattern: '/team/transfer-ownership',
    tokens: [{"old":"/team/transfer-ownership","type":0,"val":"team","end":""},{"old":"/team/transfer-ownership","type":0,"val":"transfer-ownership","end":""}],
    types: placeholder as Registry['transfer_ownership']['types'],
  },
  'invite_info': {
    methods: ["GET","HEAD"],
    pattern: '/invite/:token',
    tokens: [{"old":"/invite/:token","type":0,"val":"invite","end":""},{"old":"/invite/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['invite_info']['types'],
  },
  'serve_logo': {
    methods: ["GET","HEAD"],
    pattern: '/company-logos/:filename',
    tokens: [{"old":"/company-logos/:filename","type":0,"val":"company-logos","end":""},{"old":"/company-logos/:filename","type":1,"val":"filename","end":""}],
    types: placeholder as Registry['serve_logo']['types'],
  },
  'company_show': {
    methods: ["GET","HEAD"],
    pattern: '/company',
    tokens: [{"old":"/company","type":0,"val":"company","end":""}],
    types: placeholder as Registry['company_show']['types'],
  },
  'company_update': {
    methods: ["PUT"],
    pattern: '/company',
    tokens: [{"old":"/company","type":0,"val":"company","end":""}],
    types: placeholder as Registry['company_update']['types'],
  },
  'company_bank': {
    methods: ["PUT"],
    pattern: '/company/bank',
    tokens: [{"old":"/company/bank","type":0,"val":"company","end":""},{"old":"/company/bank","type":0,"val":"bank","end":""}],
    types: placeholder as Registry['company_bank']['types'],
  },
  'upload_logo': {
    methods: ["POST"],
    pattern: '/company/logo',
    tokens: [{"old":"/company/logo","type":0,"val":"company","end":""},{"old":"/company/logo","type":0,"val":"logo","end":""}],
    types: placeholder as Registry['upload_logo']['types'],
  },
  'search_siren': {
    methods: ["GET","HEAD"],
    pattern: '/clients/search-siren',
    tokens: [{"old":"/clients/search-siren","type":0,"val":"clients","end":""},{"old":"/clients/search-siren","type":0,"val":"search-siren","end":""}],
    types: placeholder as Registry['search_siren']['types'],
  },
  'client_list': {
    methods: ["GET","HEAD"],
    pattern: '/clients',
    tokens: [{"old":"/clients","type":0,"val":"clients","end":""}],
    types: placeholder as Registry['client_list']['types'],
  },
  'client_show': {
    methods: ["GET","HEAD"],
    pattern: '/clients/:id',
    tokens: [{"old":"/clients/:id","type":0,"val":"clients","end":""},{"old":"/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['client_show']['types'],
  },
  'client_create': {
    methods: ["POST"],
    pattern: '/clients',
    tokens: [{"old":"/clients","type":0,"val":"clients","end":""}],
    types: placeholder as Registry['client_create']['types'],
  },
  'client_update': {
    methods: ["PUT"],
    pattern: '/clients/:id',
    tokens: [{"old":"/clients/:id","type":0,"val":"clients","end":""},{"old":"/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['client_update']['types'],
  },
  'client_delete': {
    methods: ["DELETE"],
    pattern: '/clients/:id',
    tokens: [{"old":"/clients/:id","type":0,"val":"clients","end":""},{"old":"/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['client_delete']['types'],
  },
  'serve_invoice_logo': {
    methods: ["GET","HEAD"],
    pattern: '/invoice-logos/:filename',
    tokens: [{"old":"/invoice-logos/:filename","type":0,"val":"invoice-logos","end":""},{"old":"/invoice-logos/:filename","type":1,"val":"filename","end":""}],
    types: placeholder as Registry['serve_invoice_logo']['types'],
  },
  'invoice_settings_show': {
    methods: ["GET","HEAD"],
    pattern: '/settings/invoices',
    tokens: [{"old":"/settings/invoices","type":0,"val":"settings","end":""},{"old":"/settings/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['invoice_settings_show']['types'],
  },
  'invoice_settings_update': {
    methods: ["PUT"],
    pattern: '/settings/invoices',
    tokens: [{"old":"/settings/invoices","type":0,"val":"settings","end":""},{"old":"/settings/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['invoice_settings_update']['types'],
  },
  'invoice_logo_upload': {
    methods: ["POST"],
    pattern: '/settings/invoices/logo',
    tokens: [{"old":"/settings/invoices/logo","type":0,"val":"settings","end":""},{"old":"/settings/invoices/logo","type":0,"val":"invoices","end":""},{"old":"/settings/invoices/logo","type":0,"val":"logo","end":""}],
    types: placeholder as Registry['invoice_logo_upload']['types'],
  },
  'quote_next_number': {
    methods: ["GET","HEAD"],
    pattern: '/quotes/next-number',
    tokens: [{"old":"/quotes/next-number","type":0,"val":"quotes","end":""},{"old":"/quotes/next-number","type":0,"val":"next-number","end":""}],
    types: placeholder as Registry['quote_next_number']['types'],
  },
  'quote_document_count': {
    methods: ["GET","HEAD"],
    pattern: '/quotes/document-count',
    tokens: [{"old":"/quotes/document-count","type":0,"val":"quotes","end":""},{"old":"/quotes/document-count","type":0,"val":"document-count","end":""}],
    types: placeholder as Registry['quote_document_count']['types'],
  },
  'quote_set_next_number': {
    methods: ["POST"],
    pattern: '/quotes/set-next-number',
    tokens: [{"old":"/quotes/set-next-number","type":0,"val":"quotes","end":""},{"old":"/quotes/set-next-number","type":0,"val":"set-next-number","end":""}],
    types: placeholder as Registry['quote_set_next_number']['types'],
  },
  'quote_list': {
    methods: ["GET","HEAD"],
    pattern: '/quotes',
    tokens: [{"old":"/quotes","type":0,"val":"quotes","end":""}],
    types: placeholder as Registry['quote_list']['types'],
  },
  'quote_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/quotes/:id/pdf',
    tokens: [{"old":"/quotes/:id/pdf","type":0,"val":"quotes","end":""},{"old":"/quotes/:id/pdf","type":1,"val":"id","end":""},{"old":"/quotes/:id/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['quote_pdf']['types'],
  },
  'quote_factur_xml': {
    methods: ["GET","HEAD"],
    pattern: '/quotes/:id/facturx',
    tokens: [{"old":"/quotes/:id/facturx","type":0,"val":"quotes","end":""},{"old":"/quotes/:id/facturx","type":1,"val":"id","end":""},{"old":"/quotes/:id/facturx","type":0,"val":"facturx","end":""}],
    types: placeholder as Registry['quote_factur_xml']['types'],
  },
  'quote_show': {
    methods: ["GET","HEAD"],
    pattern: '/quotes/:id',
    tokens: [{"old":"/quotes/:id","type":0,"val":"quotes","end":""},{"old":"/quotes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['quote_show']['types'],
  },
  'quote_create': {
    methods: ["POST"],
    pattern: '/quotes',
    tokens: [{"old":"/quotes","type":0,"val":"quotes","end":""}],
    types: placeholder as Registry['quote_create']['types'],
  },
  'quote_update_status': {
    methods: ["PATCH"],
    pattern: '/quotes/:id/status',
    tokens: [{"old":"/quotes/:id/status","type":0,"val":"quotes","end":""},{"old":"/quotes/:id/status","type":1,"val":"id","end":""},{"old":"/quotes/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['quote_update_status']['types'],
  },
  'quote_update_comment': {
    methods: ["PATCH"],
    pattern: '/quotes/:id/comment',
    tokens: [{"old":"/quotes/:id/comment","type":0,"val":"quotes","end":""},{"old":"/quotes/:id/comment","type":1,"val":"id","end":""},{"old":"/quotes/:id/comment","type":0,"val":"comment","end":""}],
    types: placeholder as Registry['quote_update_comment']['types'],
  },
  'quote_duplicate': {
    methods: ["POST"],
    pattern: '/quotes/:id/duplicate',
    tokens: [{"old":"/quotes/:id/duplicate","type":0,"val":"quotes","end":""},{"old":"/quotes/:id/duplicate","type":1,"val":"id","end":""},{"old":"/quotes/:id/duplicate","type":0,"val":"duplicate","end":""}],
    types: placeholder as Registry['quote_duplicate']['types'],
  },
  'quote_update': {
    methods: ["PUT"],
    pattern: '/quotes/:id',
    tokens: [{"old":"/quotes/:id","type":0,"val":"quotes","end":""},{"old":"/quotes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['quote_update']['types'],
  },
  'quote_delete': {
    methods: ["DELETE"],
    pattern: '/quotes/:id',
    tokens: [{"old":"/quotes/:id","type":0,"val":"quotes","end":""},{"old":"/quotes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['quote_delete']['types'],
  },
  'invoice_next_number': {
    methods: ["GET","HEAD"],
    pattern: '/invoices/next-number',
    tokens: [{"old":"/invoices/next-number","type":0,"val":"invoices","end":""},{"old":"/invoices/next-number","type":0,"val":"next-number","end":""}],
    types: placeholder as Registry['invoice_next_number']['types'],
  },
  'invoice_document_count': {
    methods: ["GET","HEAD"],
    pattern: '/invoices/document-count',
    tokens: [{"old":"/invoices/document-count","type":0,"val":"invoices","end":""},{"old":"/invoices/document-count","type":0,"val":"document-count","end":""}],
    types: placeholder as Registry['invoice_document_count']['types'],
  },
  'invoice_set_next_number': {
    methods: ["POST"],
    pattern: '/invoices/set-next-number',
    tokens: [{"old":"/invoices/set-next-number","type":0,"val":"invoices","end":""},{"old":"/invoices/set-next-number","type":0,"val":"set-next-number","end":""}],
    types: placeholder as Registry['invoice_set_next_number']['types'],
  },
  'invoice_list': {
    methods: ["GET","HEAD"],
    pattern: '/invoices',
    tokens: [{"old":"/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['invoice_list']['types'],
  },
  'invoice_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/invoices/:id/pdf',
    tokens: [{"old":"/invoices/:id/pdf","type":0,"val":"invoices","end":""},{"old":"/invoices/:id/pdf","type":1,"val":"id","end":""},{"old":"/invoices/:id/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['invoice_pdf']['types'],
  },
  'invoice_show': {
    methods: ["GET","HEAD"],
    pattern: '/invoices/:id',
    tokens: [{"old":"/invoices/:id","type":0,"val":"invoices","end":""},{"old":"/invoices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['invoice_show']['types'],
  },
  'invoice_create': {
    methods: ["POST"],
    pattern: '/invoices',
    tokens: [{"old":"/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['invoice_create']['types'],
  },
  'invoice_convert_quote': {
    methods: ["POST"],
    pattern: '/invoices/convert-quote/:id',
    tokens: [{"old":"/invoices/convert-quote/:id","type":0,"val":"invoices","end":""},{"old":"/invoices/convert-quote/:id","type":0,"val":"convert-quote","end":""},{"old":"/invoices/convert-quote/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['invoice_convert_quote']['types'],
  },
  'invoice_update_status': {
    methods: ["PATCH"],
    pattern: '/invoices/:id/status',
    tokens: [{"old":"/invoices/:id/status","type":0,"val":"invoices","end":""},{"old":"/invoices/:id/status","type":1,"val":"id","end":""},{"old":"/invoices/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['invoice_update_status']['types'],
  },
  'invoice_unlink_quote': {
    methods: ["PATCH"],
    pattern: '/invoices/:id/unlink-quote',
    tokens: [{"old":"/invoices/:id/unlink-quote","type":0,"val":"invoices","end":""},{"old":"/invoices/:id/unlink-quote","type":1,"val":"id","end":""},{"old":"/invoices/:id/unlink-quote","type":0,"val":"unlink-quote","end":""}],
    types: placeholder as Registry['invoice_unlink_quote']['types'],
  },
  'invoice_update_comment': {
    methods: ["PATCH"],
    pattern: '/invoices/:id/comment',
    tokens: [{"old":"/invoices/:id/comment","type":0,"val":"invoices","end":""},{"old":"/invoices/:id/comment","type":1,"val":"id","end":""},{"old":"/invoices/:id/comment","type":0,"val":"comment","end":""}],
    types: placeholder as Registry['invoice_update_comment']['types'],
  },
  'invoice_duplicate': {
    methods: ["POST"],
    pattern: '/invoices/:id/duplicate',
    tokens: [{"old":"/invoices/:id/duplicate","type":0,"val":"invoices","end":""},{"old":"/invoices/:id/duplicate","type":1,"val":"id","end":""},{"old":"/invoices/:id/duplicate","type":0,"val":"duplicate","end":""}],
    types: placeholder as Registry['invoice_duplicate']['types'],
  },
  'invoice_update': {
    methods: ["PUT"],
    pattern: '/invoices/:id',
    tokens: [{"old":"/invoices/:id","type":0,"val":"invoices","end":""},{"old":"/invoices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['invoice_update']['types'],
  },
  'invoice_delete': {
    methods: ["DELETE"],
    pattern: '/invoices/:id',
    tokens: [{"old":"/invoices/:id","type":0,"val":"invoices","end":""},{"old":"/invoices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['invoice_delete']['types'],
  },
  'e_invoicing_submit': {
    methods: ["POST"],
    pattern: '/einvoicing/submit/:id',
    tokens: [{"old":"/einvoicing/submit/:id","type":0,"val":"einvoicing","end":""},{"old":"/einvoicing/submit/:id","type":0,"val":"submit","end":""},{"old":"/einvoicing/submit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['e_invoicing_submit']['types'],
  },
  'validate_connection': {
    methods: ["GET","HEAD"],
    pattern: '/einvoicing/validate-connection',
    tokens: [{"old":"/einvoicing/validate-connection","type":0,"val":"einvoicing","end":""},{"old":"/einvoicing/validate-connection","type":0,"val":"validate-connection","end":""}],
    types: placeholder as Registry['validate_connection']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
