/* eslint-disable prettier/prettier */
import type { routes } from './index.ts'

export interface ApiDefinition {
  signup: typeof routes['signup']
  verifyEmail: typeof routes['verify_email']
  resendVerification: typeof routes['resend_verification']
  login: typeof routes['login']
  twoFactorVerify: typeof routes['two_factor_verify']
  passwordResetRequest: typeof routes['password_reset_request']
  passwordReset: typeof routes['password_reset']
  logout: typeof routes['logout']
  me: typeof routes['me']
  serveAvatar: typeof routes['serve_avatar']
  profileShow: typeof routes['profile_show']
  profileUpdate: typeof routes['profile_update']
  passwordChange: typeof routes['password_change']
  uploadAvatar: typeof routes['upload_avatar']
  sessionsList: typeof routes['sessions_list']
  sessionRevoke: typeof routes['session_revoke']
  accountDelete: typeof routes['account_delete']
  twoFactorSetup: typeof routes['two_factor_setup']
  twoFactorEnable: typeof routes['two_factor_enable']
  twoFactorDisable: typeof routes['two_factor_disable']
  securityVerify: {
    sendCode: typeof routes['security_verify.send_code']
    verify: typeof routes['security_verify.verify']
  }
  createTeam: typeof routes['create_team']
  createCompany: typeof routes['create_company']
  skipCompany: typeof routes['skip_company']
  searchCompany: typeof routes['search_company']
  dashboard: {
    index: typeof routes['dashboard.index']
    stats: typeof routes['dashboard.stats']
  }
  serveIcon: typeof routes['serve_icon']
  teamList: typeof routes['team_list']
  teamCreate: typeof routes['team_create']
  teamShow: typeof routes['team_show']
  teamUpdate: typeof routes['team_update']
  uploadIcon: typeof routes['upload_icon']
  teamSwitch: typeof routes['team_switch']
  teamMembers: typeof routes['team_members']
  teamInvite: typeof routes['team_invite']
  acceptInvite: typeof routes['accept_invite']
  revokeInvite: typeof routes['revoke_invite']
  updateRole: typeof routes['update_role']
  removeMember: typeof routes['remove_member']
  transferOwnership: typeof routes['transfer_ownership']
  inviteInfo: typeof routes['invite_info']
  serveLogo: typeof routes['serve_logo']
  companyShow: typeof routes['company_show']
  companyUpdate: typeof routes['company_update']
  companyBank: typeof routes['company_bank']
  uploadLogo: typeof routes['upload_logo']
  searchSiren: typeof routes['search_siren']
  clientList: typeof routes['client_list']
  clientShow: typeof routes['client_show']
  clientCreate: typeof routes['client_create']
  clientUpdate: typeof routes['client_update']
  clientDelete: typeof routes['client_delete']
  serveInvoiceLogo: typeof routes['serve_invoice_logo']
  invoiceSettingsShow: typeof routes['invoice_settings_show']
  invoiceSettingsUpdate: typeof routes['invoice_settings_update']
  invoiceLogoUpload: typeof routes['invoice_logo_upload']
  quoteNextNumber: typeof routes['quote_next_number']
  quoteList: typeof routes['quote_list']
  quoteShow: typeof routes['quote_show']
  quoteCreate: typeof routes['quote_create']
  quoteUpdate: typeof routes['quote_update']
  quoteDelete: typeof routes['quote_delete']
}
