/* eslint-disable prettier/prettier */
import type { routes } from './index.ts'

export interface ApiDefinition {
  signup: typeof routes['signup']
  verifyEmail: typeof routes['verify_email']
  resendVerification: typeof routes['resend_verification']
  login: typeof routes['login']
  twoFactorVerify: typeof routes['two_factor_verify']
  passwordResetRequest: typeof routes['password_reset_request']
  passwordReset: typeof routes['password_reset']
  logout: typeof routes['logout']
  me: typeof routes['me']
  serveAvatar: typeof routes['serve_avatar']
  profileShow: typeof routes['profile_show']
  profileUpdate: typeof routes['profile_update']
  passwordChange: typeof routes['password_change']
  uploadAvatar: typeof routes['upload_avatar']
  sessionsList: typeof routes['sessions_list']
  sessionRevoke: typeof routes['session_revoke']
  accountDelete: typeof routes['account_delete']
  twoFactorSetup: typeof routes['two_factor_setup']
  twoFactorEnable: typeof routes['two_factor_enable']
  twoFactorDisable: typeof routes['two_factor_disable']
  securityVerify: {
    sendCode: typeof routes['security_verify.send_code']
    verify: typeof routes['security_verify.verify']
  }
  emailRequestChange: typeof routes['email_request_change']
  emailConfirmChange: typeof routes['email_confirm_change']
  createTeam: typeof routes['create_team']
  createCompany: typeof routes['create_company']
  skipCompany: typeof routes['skip_company']
  searchCompany: typeof routes['search_company']
  completePersonalization: typeof routes['complete_personalization']
  dashboard: {
    index: typeof routes['dashboard.index']
    stats: typeof routes['dashboard.stats']
    sidebarCounts: typeof routes['dashboard.sidebarCounts']
    charts: typeof routes['dashboard.charts'] & {
      revenue: typeof routes['dashboard.charts.revenue']
      collected: typeof routes['dashboard.charts.collected']
      micro: typeof routes['dashboard.charts.micro']
    }
  }
  serveIcon: typeof routes['serve_icon']
  teamList: typeof routes['team_list']
  teamCreate: typeof routes['team_create']
  teamShow: typeof routes['team_show']
  teamUpdate: typeof routes['team_update']
  teamDelete: typeof routes['team_delete']
  uploadIcon: typeof routes['upload_icon']
  teamSwitch: typeof routes['team_switch']
  teamExport: typeof routes['team_export']
  teamImport: typeof routes['team_import']
  teamMembers: typeof routes['team_members']
  teamInvite: typeof routes['team_invite']
  acceptInvite: typeof routes['accept_invite']
  revokeInvite: typeof routes['revoke_invite']
  updateRole: typeof routes['update_role']
  removeMember: typeof routes['remove_member']
  transferOwnership: typeof routes['transfer_ownership']
  inviteInfo: typeof routes['invite_info']
  serveLogo: typeof routes['serve_logo']
  companyShow: typeof routes['company_show']
  companyUpdate: typeof routes['company_update']
  companyBank: typeof routes['company_bank']
  uploadLogo: typeof routes['upload_logo']
  bankAccounts: {
    index: typeof routes['bank_accounts.index']
    show: typeof routes['bank_accounts.show']
    store: typeof routes['bank_accounts.store']
    update: typeof routes['bank_accounts.update']
    destroy: typeof routes['bank_accounts.destroy']
  }
  searchSiren: typeof routes['search_siren']
  clientList: typeof routes['client_list']
  clientShow: typeof routes['client_show']
  clientCreate: typeof routes['client_create']
  clientUpdate: typeof routes['client_update']
  clientDelete: typeof routes['client_delete']
  serveInvoiceLogo: typeof routes['serve_invoice_logo']
  invoiceSettingsShow: typeof routes['invoice_settings_show']
  invoiceSettingsUpdate: typeof routes['invoice_settings_update']
  invoiceLogoUpload: typeof routes['invoice_logo_upload']
  quoteNextNumber: typeof routes['quote_next_number']
  quoteDocumentCount: typeof routes['quote_document_count']
  quoteSetNextNumber: typeof routes['quote_set_next_number']
  quoteList: typeof routes['quote_list']
  quotePdf: typeof routes['quote_pdf']
  quoteFacturXml: typeof routes['quote_factur_xml']
  quoteShow: typeof routes['quote_show']
  quoteCreate: typeof routes['quote_create']
  quoteUpdateStatus: typeof routes['quote_update_status']
  quoteUpdateComment: typeof routes['quote_update_comment']
  quoteDuplicate: typeof routes['quote_duplicate']
  quoteUpdate: typeof routes['quote_update']
  quoteDelete: typeof routes['quote_delete']
  invoiceNextNumber: typeof routes['invoice_next_number']
  invoiceDocumentCount: typeof routes['invoice_document_count']
  invoiceSetNextNumber: typeof routes['invoice_set_next_number']
  invoiceList: typeof routes['invoice_list']
  invoicePdf: typeof routes['invoice_pdf']
  invoiceShow: typeof routes['invoice_show']
  invoiceCreate: typeof routes['invoice_create']
  invoiceConvertQuote: typeof routes['invoice_convert_quote']
  invoiceUpdateStatus: typeof routes['invoice_update_status']
  invoiceUnlinkQuote: typeof routes['invoice_unlink_quote']
  invoiceUpdateComment: typeof routes['invoice_update_comment']
  invoiceDuplicate: typeof routes['invoice_duplicate']
  invoiceUpdate: typeof routes['invoice_update']
  invoiceDelete: typeof routes['invoice_delete']
  eInvoicingSubmit: typeof routes['e_invoicing_submit']
  validateConnection: typeof routes['validate_connection']
  gmailCallback: typeof routes['gmail_callback']
  emailAccountsList: typeof routes['email_accounts_list']
  emailAccountsDelete: typeof routes['email_accounts_delete']
  emailAccountsSetDefault: typeof routes['email_accounts_set_default']
  gmailAuthUrl: typeof routes['gmail_auth_url']
  sendEmail: typeof routes['send_email']
}
