import router from '@adonisjs/core/services/router'
import { middleware } from '#start/kernel'

const InvoiceList = () => import('#controllers/invoice/list')
const InvoiceShow = () => import('#controllers/invoice/show')
const InvoiceCreate = () => import('#controllers/invoice/create')
const InvoiceUpdate = () => import('#controllers/invoice/update')
const InvoiceDelete = () => import('#controllers/invoice/delete')
const InvoiceNextNumber = () => import('#controllers/invoice/next_number')
const InvoicePdf = () => import('#controllers/invoice/pdf')
const InvoiceConvertQuote = () => import('#controllers/invoice/convert_quote')
const InvoiceDocumentCount = () => import('#controllers/invoice/document_count')
const InvoiceSetNextNumber = () => import('#controllers/invoice/set_next_number')
const InvoiceUpdateStatus = () => import('#controllers/invoice/update_status')
const InvoiceUnlinkQuote = () => import('#controllers/invoice/unlink_quote')
const InvoiceDuplicate = () => import('#controllers/invoice/duplicate')
const InvoiceUpdateComment = () => import('#controllers/invoice/update_comment')

router
  .group(() => {
    router.get('/next-number', [InvoiceNextNumber, 'handle'])
    router.get('/document-count', [InvoiceDocumentCount, 'handle'])
    router.post('/set-next-number', [InvoiceSetNextNumber, 'handle'])
    router.get('/', [InvoiceList, 'handle'])
    router.get('/:id/pdf', [InvoicePdf, 'handle'])
    router.get('/:id', [InvoiceShow, 'handle'])
    router.post('/', [InvoiceCreate, 'handle'])
    router.post('/convert-quote/:id', [InvoiceConvertQuote, 'handle'])
    router.patch('/:id/status', [InvoiceUpdateStatus, 'handle'])
    router.patch('/:id/unlink-quote', [InvoiceUnlinkQuote, 'handle'])
    router.patch('/:id/comment', [InvoiceUpdateComment, 'handle'])
    router.post('/:id/duplicate', [InvoiceDuplicate, 'handle'])
    router.put('/:id', [InvoiceUpdate, 'handle'])
    router.delete('/:id', [InvoiceDelete, 'handle'])
  })
  .prefix('/invoices')
  .use(middleware.auth())
