import router from '@adonisjs/core/services/router'
import { middleware } from '#start/kernel'

const QuoteList = () => import('#controllers/quote/list')
const QuoteShow = () => import('#controllers/quote/show')
const QuoteCreate = () => import('#controllers/quote/create')
const QuoteUpdate = () => import('#controllers/quote/update')
const QuoteDelete = () => import('#controllers/quote/delete')
const QuoteNextNumber = () => import('#controllers/quote/next_number')
const QuotePdf = () => import('#controllers/quote/pdf')
const QuoteFacturXml = () => import('#controllers/quote/pdf').then((m) => ({ default: m.FacturXml }))
const QuoteDocumentCount = () => import('#controllers/quote/document_count')
const QuoteSetNextNumber = () => import('#controllers/quote/set_next_number')
const QuoteUpdateStatus = () => import('#controllers/quote/update_status')
const QuoteDuplicate = () => import('#controllers/quote/duplicate')
const QuoteUpdateComment = () => import('#controllers/quote/update_comment')

router
  .group(() => {
    router.get('/next-number', [QuoteNextNumber, 'handle'])
    router.get('/document-count', [QuoteDocumentCount, 'handle'])
    router.post('/set-next-number', [QuoteSetNextNumber, 'handle'])
    router.get('/', [QuoteList, 'handle'])
    router.get('/:id/pdf', [QuotePdf, 'handle'])
    router.get('/:id/facturx', [QuoteFacturXml, 'handle'])
    router.get('/:id', [QuoteShow, 'handle'])
    router.post('/', [QuoteCreate, 'handle'])
    router.patch('/:id/status', [QuoteUpdateStatus, 'handle'])
    router.patch('/:id/comment', [QuoteUpdateComment, 'handle'])
    router.post('/:id/duplicate', [QuoteDuplicate, 'handle'])
    router.put('/:id', [QuoteUpdate, 'handle'])
    router.delete('/:id', [QuoteDelete, 'handle'])
  })
  .prefix('/quotes')
  .use(middleware.auth())
